### ISSUE TITLE
Not able to log in. "Too many requests" error when entering 2FA code.

### ISSUE THREAD

**Issue by djex** [microweber/microweber#1014]
I enabled 2FA for my admin account in Microweber. After submitting the 2FA code upon login the following JSON is returned to the browser:

`{"error":"Too many requests"}`

I am unable to get past this error which has locked me out of the admin account.

I am using the latest version of Microweber v1.3.4. In the mean time can someone point me in the right direction as to how I can disable 2FA so I can log in again? I'm guessing I need to edit the database just not sure what table it's under.

**Comment by NoSpamMaam** [comment]
Did you get this resolved?

**Comment by djex** [comment]
> Did you get this resolved?

No unfortunately no one replied here so I ended up restoring a backup and left 2FA disabled. Are you having the same issue?

**Comment by peter-mw** [comment]
hi, this is fixed in version 2.0.0 , can you try to update ?

**Comment by djex** [comment]
> hi, this is fixed in version 2.0.0 , can you try to update ?

I updated and can confirm 2FA is fixed and working in latest version 2.0.4. Thanks.
