### ISSUE TITLE
Impossible to manipulate block because popup is blinking

### ISSUE THREAD

**Issue by verifiera** [microweber/microweber#1018]
![image](https://github.com/microweber/microweber/assets/44637976/c2c3d683-ebe1-447d-aa8d-8ec56f9c230c)

Impossible to manipulate the block because the control popup is blinking.
On some Layouts, this popup with clone/delete is impossible to click.

A good solution will be adding buttons in the Visual Editor window to manipulate the tree.

**Comment by raikov** [comment]
Hello, thank you for your report. 
We are aware of this issue. It will be fixed in the next release.
