### ISSUE TITLE
Big BUG with reset_edit_field function in ContentManagerHelpers

### ISSUE THREAD

**Issue by mrpiagg** [microweber/microweber#1032]
Function reset_edit_field in ContentManagerHelpers class has a big bug if you customize MW a bit more than just using platform as-is.

This function has no content rel_id in data parameter and if you use placeholder with the same name on multiple pages then placeholder is deleted on all the pages!! 
It should be deleted only on the currently editing page or with an option to delete the placeholder on all the pages.
I have managed to delete content on half of my page with this.

Problematic part:
$del = \DB::table('content_fields')
->where('rel_type', '=', $item['rel'])
->where('field', '=', $item['field'])->delete();

It should have also:
->where('rel_id', '=', $content_id)

**Comment by peter-mw** [comment]
hi, thanks fore report , its fixed now in the `dev` branch

**Comment by peter-mw** [comment]
Fixed
