### ISSUE TITLE
user profile link broken

### ISSUE THREAD

**Issue by pedroponte** [microweber/microweber#1034]
the admin user profile link is broken.

It points to /admin/view:modules/load_module:users/action:profile instead of /admin/view:modules/load_module:users/

<img width="353" alt="Screenshot 2023-10-05 at 15 19 21" src="https://github.com/microweber/microweber/assets/5510270/084b3b75-84ac-4d28-865e-f7d824b9c4c6">

For now, as a workaround, I have commented the following on "public_html/userfiles/modules/users/admin.php"

**/*if ($action == 'profile') {
    print '<module type="users/profile/my_profile_admin"/>';
    return;
} else*/**if ($editUser !== false) {
    print('<module type="users/edit_user" edit-user="' . $editUser . '" />');
    return;
}

**Comment by peter-mw** [comment]
hi, thanks for report, its fixed in version 2.0
