### ISSUE TITLE
Can we include third party sites via iFrame

### ISSUE THREAD

**Issue by nickbe** [microweber/microweber#1055]
Is it possible to include another shop module via iFrame ?

**Comment by peter-mw** [comment]
Hi, you can use the embed code module and embed iframe 

![image](https://github.com/microweber/microweber/assets/5698247/41e1fd73-1198-45cb-a349-15fff85ae0cb)


paste any embed code 

![image](https://github.com/microweber/microweber/assets/5698247/350cf647-7965-4f37-a1cc-c19ae7a112da)

**Comment by nickbe** [comment]
Thank you for the information.
