### ISSUE TITLE
500 Error on /admin/ after installing with docker

### ISSUE THREAD

**Issue by continue47** [microweber/microweber#1068]
Hello,

I installed microweber with docker, accessed the IP and filled in the required detailed for installation. After that it redirected me to /admin/ which returned a 500 error.

I turned on debugging in config/app.php and this is the error:

> Vite manifest not found at: /var/www/html/public/build/manifest.json (View: /var/www/html/src/MicroweberPackages/Admin/resources/views/layouts/partials/header.blade.php) (View: /var/www/html/src/MicroweberPackages/Admin/resources/views/layouts/partials/header.blade.php) (View: /var/www/html/src/MicroweberPackages/Admin/resources/views/layouts/partials/header.blade.php)

How can I fix this?

Thank you.

**Comment by peter-mw** [comment]
did you try with `docker-compose up` or with the regular docker image ?

**Comment by continue47** [comment]
> did you try with `docker-compose up` or with the regular docker image ? 

`docker compose up -d`

After cloning the repo.

I managed to fix it by entering the container (`docker exec -it container_name bash`) and doing `npm install && npm run build`
