### ISSUE TITLE
Non-Functional Editor

### ISSUE THREAD

**Issue by SharkJohny** [microweber/microweber#1072]
Everything works great on the development environment on a local machine. 

However, when installed on a server, the template management does not work at all. Right after installation, all pages display the message: "This layout is part of the premium version of the template. 
You can install the premium version of the template to see the content of this layout. File: skin-1.php." 
Additionally, when the editor is turned on, it is impossible to edit any templates; the switch is permanently stuck on "New content".
![Snímek obrazovky 2024-04-16 v 15 33 33](https://github.com/microweber/microweber/assets/93750764/cbc88df5-0d22-4b15-a31e-a8d01e88ddfe)

**Comment by peter-mw** [comment]
Hi, can you send a video  ?

**Comment by SharkJohny** [comment]
So far, there is only a clean installation, I will give you access
https://truhlari-7331.rostiapp.cz/admin/
test@gmail.com
123456789

**Comment by peter-mw** [comment]
hi, seems the free theme layout is missing, i have updated the theme

**Comment by peter-mw** [comment]
hi, seems there is some server redirect happening all the time, maybe via htaccess or https redirect ... can you check your server config ?

**Comment by SharkJohny** [comment]
`server {
        listen       0.0.0.0:8000;
        listen       [::]:8000;



                root /srv/app;
                index index.php index.html;

        port_in_redirect off;


        location / {
            try_files $uri $uri/ /index.php$is_args$args;
        }

                location ~ \.php$ {
                try_files $uri =404;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;

                fastcgi_pass unix:/srv/run/php-fpm.sock;
                fastcgi_index index.php;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;
                fastcgi_param HTTPS on;
                }
    location /public {
        alias /srv/app/public;
    }

  location ~ /(vendor|src|config|storage|.git|.env) {
   deny all;
   return 404;
 }

        #location /static/ {
        #        alias /srv/static/;
        #}
}`


Yes, I have, when I turn it off, the files are loaded with HTTP. I've currently turned it off.

**Comment by peter-mw** [comment]
hi, no idea what can be the problem, pls send server access in discord and we will check
