### ISSUE TITLE
Validation Bug: special price Exceeds main price and Non-Numeric in add new product 

### ISSUE THREAD

**Issue by AzizulBSc** [microweber/microweber#1073]
The current validation logic doesn't adequately handle cases where the special price exceeds the main price and when these price is non-numeric value . We need to address this issue to ensure accurate pricing data validation.

![offer_price_issue](https://github.com/microweber/microweber/assets/44068019/62b1b1ea-4604-4cb7-9abe-507592a14e6d)

![price numeric issues](https://github.com/microweber/microweber/assets/44068019/f3114bd8-aefe-4bca-bb5a-18d1b2489769)

**Comment by peter-mw** [comment]
Merged, thank for the PR
