### ISSUE TITLE
CSS Live Editor impacts to all website which uses same template

### ISSUE THREAD

**Issue by yosefkurniawan** [microweber/microweber#1081]
Hi,

I have 2 website setup in config folder.
Both websites are using Big template.

In website 1, I change the global template such as colors in Template Style Editor.
I also change style of certain element in Element Style Editor.

Those change in website 1, unfortunately impacts on Website 2 as well which is not expected since Website 2 should has its own color scheme :(
![edit element style on store 1](https://github.com/microweber/microweber/assets/6382194/24b8a2ad-1aca-4008-9c1c-237b8dbc18ff)
![edited style impact on store 2](https://github.com/microweber/microweber/assets/6382194/db925cad-c00d-48f0-b902-343f18fb11cd)

**Comment by peter-mw** [comment]
Hi, we have added a fix, please check again from dev branch or update from the standalone updater by selectin dev branch

**Comment by yosefkurniawan** [comment]
Perfect @peter-mw . it works!
thank you.
