### ISSUE TITLE
Error When Replying to Comments in Admin Panel

### ISSUE THREAD

**Issue by AzizulBSc** [microweber/microweber#1082]
When I want to replay of a comment as an admin in the comment module/comment section in the admin panel , then it show following error:

![comment_replay_before](https://github.com/microweber/microweber/assets/44068019/53922cd7-7fef-4c52-ba0c-a841239ae969)

![cooment_repllay_error](https://github.com/microweber/microweber/assets/44068019/fe228f8d-41f8-45a1-b40d-686472a7a3f0)

**Comment by peter-mw** [comment]
Merged, thanks
