### ISSUE TITLE
Can't edit Shipping details

### ISSUE THREAD

**Issue by ajitbhandari** [microweber/microweber#1084]
![image](https://github.com/microweber/microweber/assets/10216870/216aeb5c-8aed-414b-8c08-4d8ab801fa2c)

after clicking on this shipping edit button it redirects to same order page

**Comment by ajitbhandari** [comment]
@peter-mw  thank you for doing this so quick

src\MicroweberPackages\Order\Models\Order.php on this file 

we also need to add two more
 **( address2,
        other_info)**
         fields so that form can update these two fields as well
```

 public $fillable = [
        'id',
        'email',
        'first_name',
        'last_name',
        'country',
        'amount',
        'payment_amount',
        'transaction_id',
        'city',
        'state',
        'zip',
        'address',
        'address2',
        'other_info',
        'phone',
        'user_ip',
        'is_completed',
        'payment_gw'
    ];

```

**Comment by peter-mw** [comment]
added them in dev branch
