### ISSUE TITLE
Module Coupons error

### ISSUE THREAD

**Issue by nandogva63** [microweber/microweber#1088]
### Discussed in https://github.com/microweber/microweber/discussions/1087

<div type='discussions-op-text'>

<sup>Originally posted by **nandogva63** May 13, 2024</sup>
**Coupon tables are not created during installation**
HTTP 500 Internal Server Error
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cart_coupons' doesn't exist (Connection: mysql, SQL: select count(*) as aggregate from `_cart_coupons`) (View: /var/www/localhost/htdocs/src/MicroweberPackages/Module/resources/views/admin/view.blade.php)PDOException  QueryException  ViewException_

### Move files from:
userfiles/modules/shop/coupons/src/database/migrations/2023_00_00_000000_create_cart_coupons_table.php
userfiles/modules/shop/coupons/src/database/migrations/2023_00_00_000001_create_cart_coupons_log_table.php
to
src/MicroweberPackages/Shop/migrations

### This fixes the error
</div>

**Comment by peter-mw** [comment]
thanks fixed
