### ISSUE TITLE
Loading shop.php instead of product.php

### ISSUE THREAD

**Issue by ajitbhandari** [microweber/microweber#1091]
after adding category in any product, It is loading full pate template instead of product page template

![image](https://github.com/microweber/microweber/assets/10216870/26e53dec-efda-4209-abe1-11b8e0cf4d47)

[natural-moisturizing-lipstick-1 is the ](http://127.0.0.1:8000/natural-moisturizing-lipstick-1) is the product page but it is loading shop layout template instead of product

I am using purchased version of big template

**Comment by peter-mw** [comment]
hi, please name the inner page as `shop_inner.php` and it should work

**Comment by ajitbhandari** [comment]
@peter-mw  thanks
