### ISSUE TITLE
Integrate payment methods

### ISSUE THREAD

**Issue by peter-mw** [microweber/microweber#207]
-  Payment on delivery
 -  Bank payment

bugs: 
- free shipping

**Comment by jojouser** [comment]
ominipay seams better and a new wheel.
 https://github.com/thephpleague/omnipay

**Comment by peter-mw** [comment]
hi @jojouser , 

yes we have considered to integrate omnipay or http://payum.org/

they both look good

just have to find some time to do it, will put it up in the todo list

**Comment by peter-mw** [comment]
omnipay is integrated in version 1.0.7, some providers are added here https://github.com/microweber/microweber/tree/master/userfiles/modules/shop/payments/gateways
