### ISSUE TITLE
Downloading backups does not work ; Microweber 0.93461

### ISSUE THREAD

**Issue by boris-chervenkov** [microweber/microweber#215]
MacOS 10.9.2
Mozilla Firefox 29.0  &  Google Chrome 34.0.1847.131
Microweber 0.93461

Steps to reproduce:
1. (optional) Create a backup and wait for the process to finish
2. Click "Download" on any backup in the list of backups

Result: new tab is opened, and JSON content is showing:

    {
        "error": "You have not provided filename to download."
    }

Tab's URL: http://example.com/api/Utils/Backup/download?file=backup_2014-May-01-114752_536234689b34f.zip

**Comment by ash-rain** [comment]
Tested. Working.
