### ISSUE TITLE
Header Editing with Liteness Template

### ISSUE THREAD

**Issue by nickwuk** [microweber/microweber#247]
I'm in the process of editing the Liteness template in Live Edit mode and noticed the following:

1) Can't seem to reposition the mouse in the h1 title text using IE11, only way seems to be using the cursor with arrow keys. Seems better in Firefox 31 except that when the anchor link edit note appears you have to click outside the box first to reposition the cursor.  

2) Can't seem to either reposition the h1 title to the centre of the header nor increase the h1 width and centralise the title text. Tried adding a 2-column layout and managed to centre the title within the first column but it had then moved outside of the h1 tags which were then empty.

3) The undo button in the top menu doesn't revert my changes in the header, it shows no history in IE11 and FF31.

4) If I select the h1 title text and the align centre button then the large font reduces to size 14px.

5) Would be useful to have some font sizes between 36 and 72px in the dropdown.

6) Would be good if each element could have the option to add eg margin or padding in live edit without having to edit the css file.

7) In admin the users dropdown does not dropdown in IE11, it does in FF31.

Hope these observations are useful, I can obviously update the layout via the css files. Not sure what the crosses do top left and bottom right of each box, maybe they identify the bounds of the grid.

Thanks,
Nick

**Comment by peter-mw** [comment]
It was cause by a bug in .mw-col

Column drag and drop fixes are added to version 1.0.7
