### ISSUE TITLE
Multi site configuration issue

### ISSUE THREAD

**Issue by jojouser** [microweber/microweber#276]
The document's "Multi site configuration" section seams outdated.
http://microweber.com/docs/developer-guide/installation/configuration
  There is no src/Microweber/bootstrap.php file in branch1.0 now.
  and also config.php does not exist.
In 1.0 branch, only need to edit database.php for a new install.
  So, how can i add multi site configuration for branch 1.0?
Thanks.

**Comment by ash-rain** [comment]
Hi,
Sorry for the confusion. We're still not ready with the code and the documentation.
However, the multisite feature should be working fine.
In order to have a second site on the same installation you need to set your DNS A record(s) to point to the same IP as your primary Microweber installation.
It should all be handled automatically afterwards - you will see the installation screen and a new subfolder will be created in the "config" directory for your new domain.
Let me know how it goes.

**Comment by jojouser** [comment]
It seams don't work and need some config.
i point two demo domain to localhost(127.0.0.1), and add two virtualhost to nginx. all the root document set to MW's location. 
the first domain works(first time, to view the url, MW will  show installer. ), but the second domain don't work(first time, when i view the second url, MW don't show installer, just show the first website. ).

**Comment by ash-rain** [comment]
Try creating an empty folder in "config", e.g. "config/second-domain.com". It might be a permission thing (I'm guessing Windows?)

**Comment by jojouser** [comment]
Yes. windows.creat empty folder don't work.
I will try to use it with debian.

**Comment by peter-mw** [comment]
Hi, 

You must rename/delete the microweber.php config file in `config/microweber.php` then it should work

**Comment by peter-mw** [comment]
Hi, we just updated the documentation on how to make it 

Check here http://microweber.com/docs/guides/installation.md

**Comment by jojouser** [comment]
i followed the document. but it seams still have problem.
step:
1. fresh install from branch 1.0
2. Microweber installation for primary/first domain works(can see the install screen)
3. create an empy file called microweber.php in config/second-domain.com/microweber.php , then visit second-domain.com, it don't show the install screen, but it shows a default home page.
Q: can i manually install the second-domain.com ? for example, manually edit the microweber.php database.php ...
thanks.

**Comment by peter-mw** [comment]
Will test the process now. 

Yes you can go manual installation too

**Comment by peter-mw** [comment]
Can you try to make 

`config/second-domain.com/microweber.php` 

to 
```
<?php return array (
  'is_installed' => 0,
);
```

**Comment by jojouser** [comment]
still don't work.

**Comment by jojouser** [comment]
log:

[2015-03-18 11:29:37] production.ERROR: exception 'PDOException' with message 'SQLSTATE[28000] [1045] Access denied for user 'forge'@'localhost' (using password: NO)' in /microweber/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:47
Stack trace:
#0 /microweber/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(47): PDO->__construct('mysql:host=loca...', 'forge', '', Array)
#1 /microweber/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(20): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#2 /microweber/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(58): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 /microweber/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(47): Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection(Array)
#4 /microweber/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(177): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'mysql')
#5 /microweber/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(65): Illuminate\Database\DatabaseManager->makeConnection('mysql')
#6 /microweber/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(304): Illuminate\Database\DatabaseManager->connection()
#7 /microweber/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(210): Illuminate\Database\DatabaseManager->__call('table', Array)
#8 /microweber/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(210): Illuminate\Database\DatabaseManager->table('options')
#9 /microweber/src/Microweber/Providers/OptionManager.php(590): Illuminate\Support\Facades\Facade::__callStatic('table', Array)
#10 /microweber/src/Microweber/Providers/OptionManager.php(590): Illuminate\Support\Facades\DB::table('options')
#11 /microweber/src/Microweber/Providers/CacheStore.php(174): Microweber\Providers\OptionManager->Microweber\Providers\{closure}()
#12 /microweber/src/Microweber/Providers/OptionManager.php(594): Microweber\Providers\CacheStore->remember('options_items_p...', '99999', Object(Closure))
#13 /microweber/src/Microweber/Database.php(34): Microweber\Providers\OptionManager->get_items_per_page()
#14 /microweber/src/Microweber/MicroweberServiceProvider.php(113): Database->__construct()
#15 /microweber/vendor/laravel/framework/src/Illuminate/Container/Container.php(773): Microweber\MicroweberServiceProvider->Microweber\{closure}(Object(Illuminate\Foundation\Application), Array)
#16 /microweber/vendor/laravel/framework/src/Illuminate/Container/Container.php(656): Illuminate\Container\Container->build(Object(Closure), Array)
#17 /microweber/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(572): Illuminate\Container\Container->make('database', Array)
#18 /microweber/vendor/laravel/framework/src/Illuminate/Container/Container.php(1231): Illuminate\Foundation\Application->make('database')
#19 /microweber/vendor/laravel/framework/src/Illuminate/Container/Container.php(1276): Illuminate\Container\Container->offsetGet('database')
#20 /microweber/src/Microweber/Providers/Modules.php(491): Illuminate\Container\Container->__get('database')
#21 /microweber/src/Microweber/functions/modules.php(13): Microweber\Providers\Modules->get('ui=any&installe...')
#22 /microweber/src/Microweber/MicroweberServiceProvider.php(156): load_all_functions_files_for_modules()
#23 [internal function]: Microweber\MicroweberServiceProvider->boot(Object(Illuminate\Http\Request))
#24 /microweber/vendor/laravel/framework/src/Illuminate/Container/Container.php(523): call_user_func_array(Array, Array)
#25 /microweber/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(631): Illuminate\Container\Container->call(Array)
#26 /microweber/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(613): Illuminate\Foundation\Application->bootProvider(Object(Microweber\MicroweberServiceProvider))
#27 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Microweber\MicroweberServiceProvider), 5)
#28 /microweber/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(614): array_walk(Array, Object(Closure))
#29 /microweber/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(15): Illuminate\Foundation\Application->boot()
#30 /microweber/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(165): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#31 /microweber/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Foundation\Application->bootstrapWith(Array)
#32 /microweber/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(103): Illuminate\Foundation\Http\Kernel->bootstrap()
#33 /microweber/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(83): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#34 /microweber/index.php(66): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#35 {main}

**Comment by peter-mw** [comment]
Hi,

I just tested it on xampp and it works here, cant reproduce it..

please make sure `config/youdomain.com/microweber.php` is writable 

also the folder `config/youdomain.com/` does not have other files in it besides "microweber.php"


If there is a file `config/youdomain.com/database.php` pls delete it

**Comment by jojouser** [comment]
i'm sure microweber.php is writeable and no other files in the config/domain.com/ folder.
i use the sqlite, not mysql , does it's the issue? i will try it later.

**Comment by peter-mw** [comment]
ok i will try too on different server

**Comment by peter-mw** [comment]
I just tried on Linux with the zip from here https://github.com/microweber/dist/raw/master/microweber-latest.zip and it working 

http://1.packages.microweber.com/2/microweber-latest/admin/
http://2.packages.microweber.com/2/microweber-latest/admin/

**Comment by jojouser** [comment]
I found the problem now.
it works with "domain.com", not work with "sub.domain.com".
for example: i use "www.domain2.com" as the second site, it don't work. but if i use "domain2.com",then it works.

**Comment by peter-mw** [comment]
Aha i see :) 

Yes the www. is replaced here https://github.com/microweber/microweber/blob/1.0/src/Microweber/MicroweberServiceProvider.php#L51

I forgot to write what down in the documentation
