### ISSUE TITLE
Remove shop not working

### ISSUE THREAD

**Issue by ehuergo** [microweber/microweber#279]
Hi,
Remove shop funtionality isn't working. The button that says "Disable online shop" saves in the database 1 or 0, meanwhile in the code of header.php (for example) use "y" or "n" ($shop_disabled = get_option('shop_disabled', 'website') == 'y')

The workaround is to change admin.php (userfiles/modules/shop/payments) to save the value "y" or "n" in the DB.
```
line: 446 
<input name="shop_disabled" class="mw_option_field"     data-option-group="website"  value="n"  type="radio"  <?php if(get_option('shop_disabled', 'website') != 'y'): ?> checked="checked" <?php endif; ?> >

line: 452
<input name="shop_disabled" class="mw_option_field"    data-option-group="website"  value="y"  type="radio"  <?php if(get_option('shop_disabled', 'website') == 'y'): ?> checked="checked" <?php endif; ?> >
```
Regards.
Eugenio.

**Comment by peter-mw** [comment]
Thanks for reporting this, i just fixed it
