### ISSUE TITLE
Url for each categories

### ISSUE THREAD

**Issue by jojouser** [microweber/microweber#282]
Now, MW can use custom url for easy page and post. but for categories,the url will be "category:ID", for example "category:29",  Can you also add custom url for category? it seams good for seo. thanks.

**Comment by jojouser** [comment]
For this issue,
 i think, MW should also have diffrent "meta title","title", etc... ,it's better for seo.

**Comment by ash-rain** [comment]
We're actually making bigger plans for SEO, but it will take some time before anything reaches production. This is where many other fail, so we want to make it right.

**Comment by ash-rain** [comment]
The URL is getting more and more irrelevant to SEO with every day. We need to focus on content and I'm thinking of running machine learning services to minimize efforts for tasks like picking keywords.

**Comment by nickwuk** [comment]
A clean url without parameters is always desirable, even if not vital for SEO then it's useful when sending in an email to a customer, it's far more user friendly.

**Comment by ash-rain** [comment]
I agree, and on that matter I also think there should be a general tool or part of the workflow (i.e. a "URL" field that's available/editable for everything). We'll see to this very soon but we're now focused on testing and releasing 1.0.4 as there are important updates to be delivered with it.

**Comment by peter-mw** [comment]
added category slug in version 1.0.7
