### ISSUE TITLE
Category saving is failing

### ISSUE THREAD

**Issue by MLoureiro** [microweber/microweber#285]
When I'm creating an category it fails because of empty columns:

```
SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'position' at row 1 (SQL: insert into `mytest_pt_categories` (`rel_id`, `data_type`, `parent_id`, `title`, `position`, `description`, `users_can_create_content`, `rel_type`, `is_deleted`, `created_at`, `updated_at`, `created_by`, `edited_by`) values (5, category, 0, test, , , 0, content, 0, 2015-03-28 15:52:18, 2015-03-28 15:52:18, 1, 1))
```

Looking at stack trace, the content is being passed as empty string `''`:

```
at Connection->runQueryCallback('insert into `chezmoi_pt_categories` (`rel_id`, `data_type`, `parent_id`, `title`, `position`, `description`, `users_can_create_content`, `rel_type`, `is_deleted`, `created_at`, `updated_at`, `created_by`, `edited_by`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', array('5', 'category', '0', 'Bazinga', '', '', '0', 'content', '0', '2015-03-28 15:52:18', '2015-03-28 15:52:18', '1', '1'), object(Closure)) in Connection.php line 570
```

AFAICT it's expecting a 0 (zero).

I'm using latest v1 (with https://github.com/microweber/microweber/commit/6f3dd9a5f05a9d8b22ea9fbf0147249d0158a55b)

**Comment by peter-mw** [comment]
I see, just updated the code, can you try now

**Comment by MLoureiro** [comment]
Nope, didn't work

**Comment by peter-mw** [comment]
Hi, can you make `dd($data)` on this line 

https://github.com/microweber/microweber/blob/1.0/src/Microweber/Providers/CategoryManager.php#L1383 

and post it here

**Comment by MLoureiro** [comment]
Here:

```
array:14 [▼
  "id" => "0"
  "table" => "categories"
  "rel" => "content"
  "rel_id" => "2"
  "data_type" => "category"
  "parent_id" => "0"
  "title" => "T-Shirt"
  "temp_5516d3fb0424f1937302666" => "2"
  "categories" => "0"
  "position" => ""
  "description" => ""
  "users_can_create_content" => "0"
  "rel_type" => "content"
  "is_deleted" => 0
]
```

**Comment by MLoureiro** [comment]
AFAICT it doesn't pass throguh DatabaseManager class, it uses Database class

**Comment by peter-mw** [comment]
see it too debugging now :)

**Comment by MLoureiro** [comment]
yep, it's faling here: https://github.com/microweber/microweber/blob/1.0/src/Microweber/Database.php#L332

And the `dd($params)`:

```
array:13 [▼
  "rel_id" => "2"
  "data_type" => "category"
  "parent_id" => "0"
  "title" => "T-Shirt"
  "position" => ""
  "description" => ""
  "users_can_create_content" => "0"
  "rel_type" => "content"
  "is_deleted" => 0
  "created_at" => "2015-03-28 16:45:45"
  "updated_at" => "2015-03-28 16:45:45"
  "created_by" => 1
  "edited_by" => 1
]

```

**Comment by MLoureiro** [comment]
I've used the same on Database 

```
        if (isset($data['position'])) {
            $data['position'] = intval($data['position']);
        }
```

And it's working, but this looks just hackish...

**Comment by peter-mw** [comment]
i just moved the save function to be mapped on the database_manager 

https://github.com/microweber/microweber/blob/1.0/src/Microweber/Database.php#L285

Can you download it again, just pushed

**Comment by MLoureiro** [comment]
Working as expected!

Thanks mate!

**Comment by peter-mw** [comment]
nice, glad it works

report if you find more of those :bug:

**Comment by MLoureiro** [comment]
Will do...
Or send the fix directly. :smile:

**Comment by peter-mw** [comment]
Thanks all fixes are welcome :) 

I re-factored the database class a bit to use the function of the database_manager class, also added unit test for this bug
