### ISSUE TITLE
price bug

### ISSUE THREAD

**Issue by jojouser** [microweber/microweber#287]
see the attachment as sample:
498.37+ 22.31 = 520.68; but it shows "Total Price: 519.37".  it is because the Shipping price is processed as "22", not "22.31".
![price-bug](https://cloud.githubusercontent.com/assets/1935044/7749379/a1f9065a-ffff-11e4-9743-7ef0b785f93b.png)

**Comment by peter-mw** [comment]
should be fixed now, we will release update in few days with other things too

**Comment by jojouser** [comment]
It seams MW still have bug for the Shipping price.
please see the sample:
step1:
![price-bug-1](https://cloud.githubusercontent.com/assets/1935044/7751395/49e68e08-000c-11e5-8405-444263c37909.png)
step2:
![price-bug-2](https://cloud.githubusercontent.com/assets/1935044/7751399/5226835c-000c-11e5-8a0e-00809b4806b1.png)
step3:
![price-bug-3-1](https://cloud.githubusercontent.com/assets/1935044/7751407/5b23a1c4-000c-11e5-9b24-4ee3e3e98163.png)
step4:
![price-bug-3-2](https://cloud.githubusercontent.com/assets/1935044/7751413/63d20824-000c-11e5-9825-db1ce22944dc.png)
when order quantity is 2, the shipping price should be still 21.36, because 2pcs's weight is still under 1kg. but MW shows the price is "21.41" (equal to 21.36+0.04)

**Comment by peter-mw** [comment]
Hi @jojouser i made the additional cost to be added if items are above 1 kg

**Comment by jojouser** [comment]
thanks for the quick fix. but It seams MW still have bug for the Shipping price. the shipping price in step4 and step5 is wrong.
please see the sample:
step1:
![price-bug-1](https://cloud.githubusercontent.com/assets/1935044/7751395/49e68e08-000c-11e5-8405-444263c37909.png)
step2:
![price-bug-2](https://cloud.githubusercontent.com/assets/1935044/7761446/712211da-0058-11e5-9974-fb4e408bd1a1.png)

step3:
![price-bug-3](https://cloud.githubusercontent.com/assets/1935044/7761449/77c48f72-0058-11e5-881c-a4671885e6dd.png)

step4: total weight is 1.5kg ; the right shipping price should be 21.31+ 1.31=22.62
![price-bug-4](https://cloud.githubusercontent.com/assets/1935044/7761450/7db8bdea-0058-11e5-9173-7367319d3bd0.png)

step5:total weight is 2kg ; the right shipping price should also be 21.31+ 1.31=22.62
![price-bug-5](https://cloud.githubusercontent.com/assets/1935044/7761456/82fad392-0058-11e5-9df4-e21b0bead56a.png)

**Comment by jojouser** [comment]
https://github.com/microweber/microweber/blob/1.0/userfiles/modules/shop/shipping/gateways/country/shipping_to_country.php
Line135 should change to            
   $calc2 = $calc * intval($total_shipping_weight);

**Comment by jojouser** [comment]
replace your file with this file https://github.com/microweber/microweber/blob/1.0/userfiles/modules/shop/shipping/gateways/country/shipping_to_country.php

Line 135 change to 
                      $calc2 = $calc * ceil($total_shipping_weight-1);

**Comment by peter-mw** [comment]
Hi @jojouser thanks for the fix, i just updated the file. Hope it works now

**Comment by jojouser** [comment]
It works now.close it.
