### ISSUE TITLE
Compatibility Postgresql and Sqlite

### ISSUE THREAD

**Issue by valle6** [microweber/microweber#290]
This CMS combines cloud plans and download options. I can use to develop my projects in my server and create sites to clients in cloud. This is rare. Using the same library become us more productive and allows code reuse. Great. 

I have an obstacle. In GitHub you says PostgreSQL and SQLite is supported (https://github.com/microweber/microweber), but in instalation page only MySQL is listed (https://microweber.com/docs/guides/start.md - recommended software). I'm accustomed with PostgreSQL and SQLite would be ideal for little projects. So I ask if do you really offer support for PostgreSQL and SQLite in accordance with the Laravel pattern? 

This is essential for me. Please answer yes. You will get a client and a contributor.

**Comment by ash-rain** [comment]
Hi there,

Thanks for the kind words, we are glad for every developer that finds MW useful.
If you read the README more carefully you'll see that ONLY drivers currently enabled/supported by your system are listed on the installation screen.
Not seeing a given database on that screen may mean one or more of the following:
* You haven't installed and/or enabled the PDO driver for that database.
* For SQLite it could mean the software itself has not been properly installed and/or configured.

So, basically, you just have to deal with this on PHP config level. One way to check the currently enabled PDO modules is to type `php -m | grep pdo` in a Linux shell. I'm not sure about Windows, though. You can just type `php -m` in command prompt and go through the list manually to see if a PDO module is missing for your database of choice.

I can't really help you in more detail as you've given me nothing on your local configuration.
I can, however, assure you the Internet is full of resources on how to enable PDO support for any major database. Just google "sqlite php pdo windows 7" or whatever applies to your setup (i.e. "ms sql server php pdo debian").

Cheers! Enjoy and share your results with Microweber! We love to see the code in action.

**Comment by ash-rain** [comment]
I assume this resolves the issue because it's been two weeks without a follow-up.
