### ISSUE TITLE
[Severe Vulnerabilties in the microweber site]

### ISSUE THREAD

**Issue by gameFace22** [microweber/microweber#291]
Hello @peter-mw 

I have sent you a mail regarding certain vulnerabilities in your microweber site.
Please do see it :)

**Comment by ash-rain** [comment]
Hi, we got your email. You can expect a reply soon.
Though it's not what you'd call a critical vulnerability we're working on it now and a fix will be available very soon.

**Comment by ash-rain** [comment]
Please don't open issues for things you are unsure of. We didn't reply your emails for a reason. The things you mentioned are in no way security vulnerabilities on their own.
