### ISSUE TITLE
about "shipping to"

### ISSUE THREAD

**Issue by jojouser** [microweber/microweber#292]
![shippingto](https://cloud.githubusercontent.com/assets/1935044/8307384/c20ad148-19f0-11e5-819f-6c80bc554a88.png)
now, the shipping to country list is all the countries, i think it's better just list the countries that we have added shipping cost in MW adminpanel. thanks.

**Comment by peter-mw** [comment]
If you have chosen "worldwide" it lists all the countries, otherwise lists only the selected. 

I will test it again

**Comment by jojouser** [comment]
yes. if no worldwide,lists only the selected.
