### ISSUE TITLE
 payment failure issue

### ISSUE THREAD

**Issue by jojouser** [microweber/microweber#297]
![20157883517](https://cloud.githubusercontent.com/assets/1935044/8560703/5acf6968-254d-11e5-8f15-2860966fb777.png)

![20157883651](https://cloud.githubusercontent.com/assets/1935044/8560941/2dcb4380-2550-11e5-9e00-6510c2b1b13a.png)

Step:
place an sample order, then (Don't do payment) choose return to website from paypal's website, it shows "mw_payment_failure=1", but the label is "successful".

**Comment by ash-rain** [comment]
Thanks for reporting this. However, this is a template issue, not a core issue. My guess is you're using the Liteness template. Its source can be found in `userfiles/templates`. We'll soon separate core code from default modules/templates but for now you can submit a pull request in this repository if you fix it first. We currently have other project priorities so this can take a while to get some attention. It's a matter of simple check to make it work the way it should.
