### ISSUE TITLE
Fatal error when reorder menu item

### ISSUE THREAD

**Issue by votong** [microweber/microweber#309]
I found a error when reorder menu item.
It caused by undefined variable $table in file src/Microweber/Providers/MenuManager.php line 724.
I fixed it by replace variable $table with string "menus"

**Comment by peter-mw** [comment]
This is fixed in 1.0.5 

Please install with

`composer create-project microweber/microweber my_site 1.0.5.x-dev --prefer-dist --no-dev --no-plugins --no-scripts --ignore-platform-reqs`

**Comment by ash-rain** [comment]
And to make the command longer add `--depth 1` to get just the tip of the repository :)
