### ISSUE TITLE
Deleted data remain in database

### ISSUE THREAD

**Issue by Dalboz** [microweber/microweber#312]
Why deleted data like categories, products, etc remains as records in the database?
I think they should be removed accordingly because the collide with other functions, for example the search function, when you look in there :ghost:  products appear

**Comment by ash-rain** [comment]
The behaviour you witnessed is a bug, but instead we should fix the search function to exclude deleted content. A good CMS should make it very hard for you to lose (accidentally delete) data, so please open issues for colliding functions.
