### ISSUE TITLE
Table stats_pageviews issue

### ISSUE THREAD

**Issue by jojouser** [microweber/microweber#314]
1.0.5 branch, view the site's frontpage, it show this issue:

QueryException in Connection.php line 624:
SQLSTATE[HY000]: General error: 1 no such table: stats_pageviews (SQL: select "id" from "stats_pageviews" where "page_id" = 1 limit 1)

PDOException in Connection.php line 292:
SQLSTATE[HY000]: General error: 1 no such table: stats_pageviews

**Comment by ash-rain** [comment]
What was the issue? Was it local?

**Comment by jojouser** [comment]
it was fixed in  be29e71  .
