### ISSUE TITLE
Firefox changing content

### ISSUE THREAD

**Issue by nexxterra** [microweber/microweber#316]
I came across a strange issue today in MW... When editing in Firefox, their auto translate changed text on the page to different text while I was doing something totally unrelated I tracked down the source of the problem to FF and as I use no add ons or plugins, I went to the preferred language and deleted ALL languages that showed... MW needs to somehow block this from happening!

**Comment by ash-rain** [comment]
I don't think it's possible to block the auto-translate. Chrome also have this feature and I'm pretty sure Microsoft will soon include it with Edge.
Anyway, I'll look into this, but for the time being you should disable auto-translate for your Microweber websites.

**Comment by peter-mw** [comment]
fixed in version 1.0.7
