### ISSUE TITLE
talErrorException in MicroweberServiceProvider.php line 50:

### ISSUE THREAD

**Issue by jojouser** [microweber/microweber#317]
Class 'Microweber\Utils\Adapters\Config\ConfigSave' not found

in MicroweberServiceProvider.php line 50

**Comment by ash-rain** [comment]
Please give more details. How did you get this exception?
Is it a clean install or did you do something? Be more expressive.

**Comment by jojouser** [comment]
branch 1.0.5 latest version.

**Comment by ash-rain** [comment]
Why don't you create pull requests for such small changes? Don't be afraid to contribute :-)

**Comment by peter-mw** [comment]
Hi, you can download the 1.0.5 branch as zip from here https://github.com/microweber/microweber/archive/1.0.5.zip and replace your `src` folder
