### ISSUE TITLE
Install error - /vendor/autoload.php missing

### ISSUE THREAD

**Issue by nickwuk** [microweber/microweber#322]
I've uploaded v1.0.5 and the install give error 500, the error in the server log says:
PHP Warning:  require(/home/myaccountname/public_html/myfoldername/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /home/eshop/public_html/easy-websites/bootstrap/autoload.php on line 17

There's no vendor folder in the source zip.

**Comment by peter-mw** [comment]
hi nick, that's strange

i just pushed some updates to the zip

can you try with the file from here https://github.com/microweber/dist/raw/master/microweber-latest.zip
