### ISSUE TITLE
Url issue for subpage/post/product.

### ISSUE THREAD

**Issue by jojouser** [microweber/microweber#324]
add a post(url is "new-test") to blog page, then the full url for the post should be "domain.com/blog/new-test",
but now, the full url is "domain.com/new-test"

**Comment by ash-rain** [comment]
You can type any "slug" for your post. This is not an issue, it's by design to allow you to have any url convention.

**Comment by lckamal** [comment]
why do we need double url on slug? I think its better to remove site_url from url. eg. http://take.ms/jkFlQ

**Comment by peter-mw** [comment]
hi, this is fixed from few weeks ago, please update your site from this zip https://github.com/microweber/dist/raw/master/microweber-update.zip
