### ISSUE TITLE
Create a new layout

### ISSUE THREAD

**Issue by Nawincbe** [microweber/microweber#327]
Can you please tell me to create a new layout style....

**Comment by Staalkoper** [comment]
Hi Nawincbe,

If I understand your question you want to create a own template?
A basic documentation on how to develop a own Microweber template can be found at http://microweber.com/docs/guides/templates_101.md

**Comment by Nawincbe** [comment]
Thank you for your quick reply Staalkoper.,
I am asking about new layout like 4 pictures and 4 pictures with text...., Actually i create a config file and normal design file and image but i did't see the layout style dropdown.... Please help me..., 
One more doubt is if i delete <p>your text is here</p> tag after that i can't create new row!!!

**Comment by Staalkoper** [comment]
I'm not sure what you want to achieve now Nawincbe,
Do you want a Layout with 4 rows which has an image and text in every row?

**Comment by Nawincbe** [comment]
Yes

**Comment by Staalkoper** [comment]
At the moment this layout, as you have already noticed, haven't been added yet.

I will have a look if I can make a layout but for the time being you could do as I have shown you in the video below
http://screencast.com/t/tEUrq3GwnC

Hope that this solved your problem.

**Comment by Nawincbe** [comment]
Great..., but you edit in live edit mode i am trying to do with admin edit panel

**Comment by Staalkoper** [comment]
Why do you want to try to do it through the "admin edit panel" and not "live edit mode"?

**Comment by Nawincbe** [comment]
I have some problems in live edit mode this is my website link www.infodatasphere.com now I need at the moment result....

**Comment by Staalkoper** [comment]
I barely got experience with the "Admin Edit Panel" but you could try something like this as shown belown.
http://screencast.com/t/o44RWWESOdr

If you cant find make it work like that than I guess your destiny is to wait for support from @microweber

**Comment by Nawincbe** [comment]
okay thanks for your time Staalkoper....
