### ISSUE TITLE
Issue with theming the form-fields

### ISSUE THREAD

**Issue by Thomaxo** [microweber/microweber#329]
Hi,

My issue is with theming the custom_fields module.
It provides no way of manipulating how the form fields are generated.
Everything is "hidden" behind this function:   <?php  print  mw()->fields_manager->make($field);   ?>

Where can i find this function/how can i manipulate it?

Thanks

**Comment by peter-mw** [comment]
Hello @Thomaxo ,

there is still no documentation on theming the custom fields

for now you can follow the next steps

1) Copy the custom fields you want to style from https://github.com/microweber/microweber/tree/master/userfiles/modules/microweber/custom_fields

2) Make a folder in your template called `modules/custom_fields` 

3) Paste the file there for example `userfiles/templates/your_template_folder/modules/custom_fields/dropdown.php`

**Comment by peter-mw** [comment]
There is also another simpier way

You can also pass a `input_class` as parameter to the make functions



For example:
`
$field['input_class'] = "large-field";
print mw()->fields_manager->make($field); 
`

**Comment by Thomaxo** [comment]
Steps 1 to 3 worked perfectly! Thanks :)
