### ISSUE TITLE
icon selector, variable theme-icons

### ISSUE THREAD

**Issue by Thomaxo** [microweber/microweber#331]
Hi,

My issue isn't exactly a issue but a nuisance.
The current way the icon-choosing works is by putting css icon classes into the input-field in the admin modal. You can put any class there, so technically no problem.

However, to help, there is some javascript that is requested to give you a list of icons you can choose.

this is the javascript that does that (in the admin modal): 
```javascript
$('.tab-icon').on("change", function (e, el) {
        				 tabs.save();
        			});
        			 $('.tab-icon').on("click", function (e, el) {
        				el = $(this)[0];
        				mw.iconSelector._activeElement = el;
        				mw.iconSelector.popup(true);
        			}); 
 ```

This is all fine if you only wish to use standard microweber icons. I don't :)
The function that is pulled from userfiles/modules/microweber/api/wysiwyg.js starts on line 1673.
It seems to pull icons from ui.css, font-awesome.css, semantic.css. (the last 2 probably don't work).

This is where my question gets interesting:
Wouldn't it be much more interesting if you could put css files as variables, as well as the classes it needs to find?
For example:

```javascript
$('.tab-icon').on("change", function (e, el) {
        				 tabs.save();
        			});
        			 $('.tab-icon').on("click", function (e, el) {
        				el = $(this)[0];
        				mw.iconSelector._activeElement = el;
        				mw.iconSelector.popup(true);
         				mw.iconSelector.css( <?= $cssFile ?> );
        				mw.iconSelector.css( <?= $indexClass ?> );
        			}); 
 ```

This way you get variable icons, and if possible implement a foreach loop in the javascript as well.
(of which there were already plans of i see, iconFontClasses: [];  !!!)

**Comment by peter-mw** [comment]
hi @Thomaxo you can now use custom icons

you must make a CSS file and define the icon classes there 

when the live edit is loaded the icon selector will look for stylesheets with `data-iconset=true` attribute and parse it


for example in your template 
```html
<link rel="stylesheet" href="{TEMPLATE_URL}css/icons.css" type="text/css" media="all" data-iconset=true>
```

**Comment by Thomaxo** [comment]
Thats awesome! Which files do i need to replace in my current install? And, how do i define the index? .mw-icon, .fa-...
