### ISSUE TITLE
How to deal with $(document).ready(function().... things with updating modules/ajax

### ISSUE THREAD

**Issue by Thomaxo** [microweber/microweber#332]
Hi,

My issue is javascript functions which run on document ready.
(for example masonry).

How do i implement a   $(ajax).ready(function().... in microweber?
Or more precisely,

$(when microweber and the browser finished updating the module).ready(function()..

**Comment by peter-mw** [comment]
hi, the $(document).ready function works when the module loads or its realoded

in your module's `index.php` you can put 

```html
<script>
$( document ).ready(function() {
  alert('hi')
});
</script>
```
and it will work
