### ISSUE TITLE
feature request: rel: "module"?

### ISSUE THREAD

**Issue by Thomaxo** [microweber/microweber#335]
Not exactly sure about this one.. but it would seem interesting to me if the editable fields related to the module in question.
This way you can dynamically detect for which module type it is, and save it like that in the database.

Why do i think this would be useful? 
1) shorter database query's (?)
2) modules with editable fields then gain the ability to be swapped out and put into different pages.

**Comment by ash-rain** [comment]
I think it would over complicate the database schema for too little gain.
We use Eloquent a lot so DB queries should be more or less optimal, at least in most cases. Do you have any specific concerns?

**Comment by Thomaxo** [comment]
I'm not sure of anything i'm going to write here relating to the database.. :) Here it goes:

I'm building a block-based theme, which means i basically don't have page-templates.
You start of blank and then drag modules/blocks to form your layout.
This means i basically never make use of the "content" relationship and make up my own relationships as i go.

My modules themselves do contain layouts, and often a lot of editable fields.
I set the rel's as the name of my module, which probably achieves the same goal as i wanted to achieve in this post.

<div class="edit" field="module-id-field-id" rel="slideshow" > blabla </div>
The query probably searches through a table containing only fields with rel = slideshow,
pretty well optimized.

Now, i do this for every module. rel="slideshow", rel="tabs",  rel="imageAndText"........
Might be more interesting to just have rel="module" and swap out module with the module name automatically? This way you could also automatically attach an id attribute so the query has more "limiters" when looking through the database, and thus probably quicker results? (instead of field="module-id-field-id" in which all the fields relating to a module are one gigantic list)

This also lays a foundation for injecting variables(other text) into the editable fields outside of live edit.
(CRUD-database) This could also work the other way around, as both live-edit and CRUD could relate to the same database.


Again, i don't know a lot about databasing, or even programming. Just an idea? :)

**Comment by Thomaxo** [comment]
Closed for being not useful :)

**Comment by peter-mw** [comment]
You can put any value in the `rel` parameter then you can query it as 

`mw->content_manager->edit_field("rel_type=slideshow&field=module-id-field-id");`
