### ISSUE TITLE
issue with thumbnail($src, $width, $height)

### ISSUE THREAD

**Issue by Thomaxo** [microweber/microweber#337]
Hi,
resizing is only based on $width, no cropping taking place.
(or only based on $height i guess, either one)

So basically it doesn't do cropping?
Might be interesting to extend the function to something like:
thumbnail($src, $width, $height, $cropping="true")

edit:
extend it to thumbnail($src, $width $height, $cropping="true" $delete="true")
($delete = 'no' => places white edges, $delete = 'y' => removes the minimum amount to achieve aspect ratio)

Why? Why not crop them yourself?

I'm lazy, people are lazy. Sure, if i want control over how everything is cropped i'll do the effort.
But, as often is the case, people have a big list of 16:10 images, or some other ratio,
the slideshow happens to amazing 16:9 ratio, or you have all kinds of images in somewhat the same shape, but not exactly.

I've looked at the function in src/Microweber/Providers/MediaManager.php line 873 to 940
Doesn't seem like a big hassle to implement http://php.net/manual/en/function.imagecrop.php
But i'm not too confident about my programming skill yet to mess in the source code that deep.

Cheers!

**Comment by peter-mw** [comment]
hi @Thomaxo i am looking to implement this class https://github.com/JBZoo/Image or something else to deal with images.

**Comment by peter-mw** [comment]
thumbnail class updated in version 1.0.7
