### ISSUE TITLE
Cannot delete pages or menus

### ISSUE THREAD

**Issue by shchukax** [microweber/microweber#344]
I'm using version 1.0.7.  Apparently, I can't delete any pages.  If I navigate to the list of pages in admin and try to delete it, the page seems to be deleted, but then it's back.  This happens with any page, regardless of whether it's added to a menu, whether it's got a parent page, etc.  The only way I found to delete the page is to manually delete the row from `content` table in the database and then in the advanced section of admin reload the database.

The same apparently applies to menus, except I have to delete that menu from pages that contain it before deleting it from the database, otherwise it'll be reinserted into the database with empty content.

**Comment by peter-mw** [comment]
this is strange... it has been fixed few days ago 

can you try to replace the `src` folder with the one from this zip 

https://github.com/microweber/dist/raw/master/microweber-latest.zip

**Comment by shchukax** [comment]
Oh, ok.  My install is from about  a week ago.  Can you point out which files have changed for this?  I don't want to replace the whole src dir, as I've made some customisations.

**Comment by peter-mw** [comment]
replace 2 files
`src/Microweber/Providers/Content/ContentManagerHelpers.php` and `src/Microweber/functions/api_callbacks.php` 

this should fix the error

**Comment by shchukax** [comment]
Thanks! Yes, this fixes the problem.

**Comment by peter-mw** [comment]
Cool, i am glad it works, 

will leave this issue open for few days in case someone else has this problewm
