### ISSUE TITLE
Microweber in FreeBSD jail with PHP-FPM and Nginx in FastCGI mode behind Nginx reverse proxy in different jail

### ISSUE THREAD

**Issue by chlarsen** [microweber/microweber#345]
Dear All,
I seem to have a really weird problem that I have not been able to solve and never encountered with other PHP applications:
I have installed Microweber in a FreeBSD jail (if you are not familiar with FreeBSD and jails, just consider them different servers), and can access the instance happily, with all graphics and templates showing up. Yes - your Nginx settings have been set in accordance to what is found here: https://github.com/alvsgithub/microweber
I run the application server behind a caching reverse proxy using Nginx, and with PHP I usually need nothing but this:
```
# handle default location
location                        / {
    # naxsi rules, apply to / as first configuration entry
    include                     naxsi_default.rules;
    # enable proxy cache
    proxy_cache                 microweber_proxy_cache;
    expires                     7d;
    # try to serve static files from Nginx
    try_files                   $uri @microweber;
}
location                        @microweber {
    proxy_pass                  http://www_php.jail.vlan:[microweber application port];
}
```
And things work like a charm. However, this is not the case with Microweber: PHP code is indeed displayed, but all assets do not show up, means I get a raw page. However, all assets are accessible, so this is not a permission issue. Does Microweber deal with assets and templates and such in a somewhat special way that requires my to add in more details into the Nginx reverse proxy configuration?
Thank you so much for your help,
Chris

**Comment by chlarsen** [comment]
Update: I had an automatic redirection to https:// built into my caching reverse proxy. Allowing access via plain http:// show the proper Microweber site with all its toys and whistles. This is a wee bit strange, because I think that this is pretty standard for http:// to https:// redirection:
```
# handle default location
location                        / {
    # redirect to https
    return                      301 https://$host$request_uri;
}
```
But evidently, it does not seem to do the trick. Any ideas. Seems to be Microweber-specific, as I have not encountered this issue elsewhere, or am I missing sth?
Thanks a lot!
Chris

**Comment by chlarsen** [comment]
Seems that the redirection of all assets to https:// does not work (for unknown reasons), and those over-protective black-box browsers (such as Firefox and Chromium) just show the SSL'd content...
I still cannot put my finger on the issue, why the site is not redirected to https:// completely. Any ideas..
Thanks a lot, Chris

**Comment by chlarsen** [comment]
Heavyweight workaround: Run Nginx with FastCGI with SSL enabled and channel all requests through https even in the application backend. A bit expense, really: The reverse proxy should do SSL, nothing else. Essentially, there must be a setting at the Microweber application level that say: "Use https:///[my.host]" only. Thoughts? Cheers!
Chris

**Comment by peter-mw** [comment]
hi @chlarsen i really haven't used Microweber in a setup like yours 


in apache the .htaccess rule is

```
<IfModule mod_rewrite.c>
RewriteCond %{HTTPS} !=on
RewriteRule .* https://%{SERVER_NAME}%{REQUEST_URI} [R,L]
</IfModule>
```
which redirect non https user to https

i have dont have much experience with Nginx and dont have a clue how to do it. 

If someone knows how to setup the reverse proxy, please post here

Another way is to add this PHP code to the top of your index.php

```
if(!isset($_SERVER['HTTPS']) || $_SERVER['HTTPS'] == ""){
    $redirect = "https://".$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
    header("HTTP/1.1 301 Moved Permanently");
    header("Location: $redirect");
    exit;
}
```

**Comment by chlarsen** [comment]
Thanks a lot, Peter, for your response. Alas, it does not work. Luckily I got it to work using SSL throughout. Maybe someone else has a suggestion? Thanks a lot! Chris

**Comment by peter-mw** [comment]
hi @chlarsen

there is one tutorial which may help you, there are some Nginx rewrite rules which may be useful

https://www.rosehosting.com/blog/install-microweber-ubuntu-14-04/

**Comment by chlarsen** [comment]
Thanks, Peter, I actually went through this. As I said, the issue was that the application produces mixed SSL'd and non-SSL'd data, unless I run Nginx with FastCGI in SSL mode throughout. I will test the uploading function by bypassing the reverse proxy and let you know. Thanks!

**Comment by chlarsen** [comment]
No, Peter, my reverse proxy redirection was perfect: The "cannot upload issue" that you have already closed is NOT due to that. I have followed your instructions by the letter, Microweber and Nginx with FastCGI plus PostgreSQL are sitting together with PHP-FPM in one jail, and are accessed directly, via SSL. No reverse proxy (for testing). Still the "Not found!" warning. How experienced are your with PostgreSQL? I ask, because a lot of PHP apps do run very well on MySQL/MariaDB, but show unpredictable behaviour with PostgreSQL, mainly due to the focus MySQL/MariaDB are receiving in the PHP world. I personally prefer PostgreSQL vastly. If you have no know issue with PostgreSQL - god. But if it is a bit of a grey area, I better stay away from PostgreSQL... Any thoughts?  As always: Thanks a lot! Chris

**Comment by chlarsen** [comment]
Related - I guess:

even with a MySQL-based installation, without reverse proxy, the app ignores my specific MySQL setttings entered via the browser, and produces this:
```
PDOException in Connector.php line 47:
SQLSTATE[HY000] [2002] No such file or directory
in Connector.php line 47
at PDO->__construct('mysql:host=localhost;dbname=forge', 'forge', '', array('0', '2', '0', false, false)) in Connector.php line 47
at Connector->createConnection('mysql:host=localhost;dbname=forge', array('driver' => 'mysql', 'host' => 'localhost', 'database' => 'forge', 'username' => 'forge', 'password' => '', 'charset' => 'utf8', 'collation' => 'utf8_unicode_ci', 'prefix' => '', 'name' => 'mysql'), array('0', '2', '0', false, false)) in MySqlConnector.php line 20
at MySqlConnector->connect(array('driver' => 'mysql', 'host' => 'localhost', 'database' => 'forge', 'username' => 'forge', 'password' => '', 'charset' => 'utf8', 'collation' => 'utf8_unicode_ci', 'prefix' => '', 'name' => 'mysql')) in ConnectionFactory.php line 58
at ConnectionFactory->createSingleConnection(array('driver' => 'mysql', 'host' => 'localhost', 'database' => 'forge', 'username' => 'forge', 'password' => '', 'charset' => 'utf8', 'collation' => 'utf8_unicode_ci', 'prefix' => '', 'name' => 'mysql')) in ConnectionFactory.php line 47
at ConnectionFactory->make(array('driver' => 'mysql', 'host' => 'localhost', 'database' => 'forge', 'username' => 'forge', 'password' => '', 'charset' => 'utf8', 'collation' => 'utf8_unicode_ci', 'prefix' => ''), 'mysql') in DatabaseManager.php line 177
at DatabaseManager->makeConnection('mysql') in DatabaseManager.php line 65
at DatabaseManager->connection() in DatabaseManager.php line 304
at DatabaseManager->__call('table', array('modules')) in Facade.php line 210
at DatabaseManager->table('modules') in Facade.php line 210
at Facade::__callStatic('table', array('modules')) in DatabaseManager.php line 668
at DB::table('modules') in DatabaseManager.php line 668
at DatabaseManager->table('modules') in DatabaseManager.php line 124
at DatabaseManager->get(array('installed' => '1', 'limit' => '1000', 'table' => 'modules', 'group_by' => 'module', 'order_by' => 'position asc', 'cache_group' => 'modules/global')) in Modules.php line 469
at Modules->get('ui=any&installed=1&limit=99999') in modules.php line 10
at load_all_functions_files_for_modules() in MicroweberServiceProvider.php line 212
at MicroweberServiceProvider->boot(object(Request))
at call_user_func_array(array(object(MicroweberServiceProvider), 'boot'), array(object(Request))) in Container.php line 523
at Container->call(array(object(MicroweberServiceProvider), 'boot')) in Application.php line 690
at Application->bootProvider(object(MicroweberServiceProvider)) in Application.php line 672
at Application->Illuminate\Foundation\{closure}(object(MicroweberServiceProvider), '7')
at array_walk(array(object(EventServiceProvider), object(RoutingServiceProvider), object(AppServiceProvider), object(EventServiceProvider), object(RouteServiceProvider), object(HtmlServiceProvider), object(MarkdownServiceProvider), object(MicroweberServiceProvider), object(AuthServiceProvider), object(ControllerServiceProvider), object(CookieServiceProvider), object(DatabaseServiceProvider), object(EncryptionServiceProvider), object(FilesystemServiceProvider), object(FormRequestServiceProvider), object(FoundationServiceProvider), object(PaginationServiceProvider), object(SessionServiceProvider), object(ValidationServiceProvider), object(ViewServiceProvider), object(CacheServiceProvider)), object(Closure)) in Application.php line 673
at Application->boot() in BootProviders.php line 15
at BootProviders->bootstrap(object(Application)) in Application.php line 183
at Application->bootstrapWith(array('Illuminate\Foundation\Bootstrap\DetectEnvironment', 'Illuminate\Foundation\Bootstrap\LoadConfiguration', 'Illuminate\Foundation\Bootstrap\ConfigureLogging', 'Illuminate\Foundation\Bootstrap\HandleExceptions', 'Illuminate\Foundation\Bootstrap\RegisterFacades', 'Illuminate\Foundation\Bootstrap\RegisterProviders', 'Illuminate\Foundation\Bootstrap\BootProviders')) in Kernel.php line 199
at Kernel->bootstrap() in Kernel.php line 110
at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 84
at Kernel->handle(object(Request)) in index.php line 72
```
Redoing the process manually via dtabase.php.

**Comment by chlarsen** [comment]
All the above do not take away the upload error. Sorry.

**Comment by peter-mw** [comment]
hi @chlarsen can you manually edit the file `config/database.php` and check if the database credentials are saved there. 

the upload error is related to something else, not the database

Can you check if this link is resolving http://example.com/plupload

**Comment by peter-mw** [comment]
ping @ash-rain , maybe you can have some idea?

**Comment by ash-rain** [comment]
Thanks @chlarsen, great questions!
I think you are the first to give feedback on FreeBSD setup :) awesome stuff, I'd love to help.
We've only done been testing throughout on Linux and Windows so far, so in theory you should be prepared for surprises.
I'm not sure if I understand your setup enough but sounds like something the reverse proxy should solve. I've done my fair share of nginx setups and I'd love to help but I'll ask you to share some ssl config, I suspect you could possibly be doing something wrong there.
Rock on with MW!

**Comment by chlarsen** [comment]
Dear Ash, dear Peter,
Thanks a lot for your encouragement. As I am a bit at the end of my tether, I have attached my installation journals of (1) the reverse proxy (sitting in a FreeBSD jail called ''secure''), (2) my PHP application jail (aptly called ''www_php'', with its own Nginx instance running FastCGI and doing the PHP deed via FPM, and (3) the Microweber instance installation, using ''git''  and ''composer install'' to keep installation and upgrade simple. 

SUMMARY OF FINDINGS SO FAR:
(1) I have further tested both MariaDB as well as PostgreSQL (and would personally always prefer PostgreSQL). However, the PostgreSQL-based installation process continues to be erratic, as described in '#319: MySQL/MariaDB works most of the times, and does not need a prefix, while PostgreSQL does not work at all without a prefix. I note that the installation mask does take in all the settings entered previously into database.php, except the name of the database and the prefix - which is a bit weird.
(2) "Not found!" as per previously posted screenshots, whenever there is a file to be uploaded. This applies to situation with and without reverse proxy: I tested both situations, NATting accordingly. 

Kindly regard the attached documentation as possible building bricks of an installation guide for FreeBSD...

[set_up_the_secure_jail_-_your_secure_proxy_server.pdf](https://github.com/microweber/microweber/files/183369/set_up_the_secure_jail_-_your_secure_proxy_server.pdf)
[set_up_the_www_php_jail_-_your_php_web_application_server.pdf](https://github.com/microweber/microweber/files/183370/set_up_the_www_php_jail_-_your_php_web_application_server.pdf)
[install_and_configure_microweber.pdf](https://github.com/microweber/microweber/files/183371/install_and_configure_microweber.pdf)

Apologies for dumping this on you - but I am stuck, especially, as tis does not seem to be a reverse proxy server nor a permission issue... Guess I am missing something obvious!
Thanks a lot!

Chris

**Comment by chlarsen** [comment]
I had a careful look at Nginx's logs, and noted this log entry, when I created and edited a page with text first, and then tried to add a picture:

```
From: 113.162.125.119 | Time: 22/Mar/2016:03:15:31 +0100 | Cache status: - | Cache control: private, must-revalidate | Cache expires: -1 | Request: GET /editor_tools/rte_image_editor HTTP/1.1 | Status: 200 | Body sent: 595b | Requested: 822b | Total sent: 1438b | Referrer: https://www.caocuero.com/test-text-page | User agent: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0 | Request time: 0.096ms | Compression: 2.49 
From: 113.162.125.119 | Time: 22/Mar/2016:03:15:31 +0100 | Cache status: - | Cache control: - | Cache expires: - | Request: GET /userfiles/modules/microweber/api/editor_externals.js?mwv=1.0.7&_=1458612931445 HTTP/1.1 | Status: 200 | Body sent: 114b | Requested: 955b | Total sent: 575b | Referrer: https://www.caocuero.com/editor_tools/rte_image_editor | User agent: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0 | Request time: 0.001ms | Compression: 1.02 
```
While '' '' exists, the referrer URL (''https://www.caocuero.com/editor_tools/rte_image_editor'') does not. Still, the system does not report an error, unless an image editor frame pops up.
Does this help? Thanks for your thoughts!
Chris

**Comment by peter-mw** [comment]
hi @chlarsen can you send me access to your server on my email, i want to login and try to debug it in the current environment

**Comment by chlarsen** [comment]
Dear Peter, good to hear from you. As much as I would love to give you access, I am not allowed to do that. I hope you will understand. However, if you can tell me exactly what to do, I can run the commands for you, and send you the output. One of the most helpful deebugging informaion might be my input above re. a missing file from the Nginx logs. Quote:
-------------------------------------------------%<-----------------------------------
I had a careful look at Nginx's logs, and noted this log entry, when I created and edited a page with text first, and then tried to add a picture:

From: 113.162.125.119 | Time: 22/Mar/2016:03:15:31 +0100 | Cache status: - | Cache control: private, must-revalidate | Cache expires: -1 | Request: GET /editor_tools/rte_image_editor HTTP/1.1 | Status: 200 | Body sent: 595b | Requested: 822b | Total sent: 1438b | Referrer: https://www.caocuero.com/test-text-page | User agent: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0 | Request time: 0.096ms | Compression: 2.49 
From: 113.162.125.119 | Time: 22/Mar/2016:03:15:31 +0100 | Cache status: - | Cache control: - | Cache expires: - | Request: GET /userfiles/modules/microweber/api/editor_externals.js?mwv=1.0.7&_=1458612931445 HTTP/1.1 | Status: 200 | Body sent: 114b | Requested: 955b | Total sent: 575b | Referrer: https://www.caocuero.com/editor_tools/rte_image_editor | User agent: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0 | Request time: 0.001ms | Compression: 1.02 

While ''/userfiles/modules/microweber/api/editor_externals.js?'' exists, the referrer URL (''https://www.caocuero.com/editor_tools/rte_image_editor'') does not. Still, the system does not report an error, unless an image editor frame pops up.
-------------------------------------------------%<-----------------------------------
Indeed, microweber/editor_tools/* does not exist at all. Composer error? It does not throw any error, though. PHP functions have been tested both with and without restrictions, with and without Suhosin. Let me know what t do to be your hands on the server Sorry for the hassle, and thanks a million!
Chris

**Comment by chlarsen** [comment]
I have been observing Nginx access logs again today. It seem a whole class of function s never got installed, as evidenced by the unsuccessful call for "microweber/editor_tools" . That very directory just does not exist - anywhere. There is something missing from the installation procedure, possibly? Any thoughts or ideas?
Thanks a lot,
Chris

**Comment by chlarsen** [comment]
Update I note failures at several levels: Installing templates does not work. A zero byte length shopmag file is created in userfiles/templates/ but that is all. Permissions seem to be ok; in creasing the memory execution limit does not solve the problem. What kind of PHP settings does Microweber need and what are the permissions again, or are those in the README alright?
Something is fundamentaly flawed, and it is something simple, but it seemingly is not documented - or I am blind :-). Thank you! Chris

**Comment by peter-mw** [comment]
hi @chlarsen its really hard to debug like that in blind :)

Maybe the PHP `$_REQUEST` array is not populated or something

Also the `$_SERVER['HTTP_REFERER']` variable may be missing

Can you put dd($_REQUEST) and dd($_SERVER) on [this line](https://github.com/microweber/microweber/blob/master/src/Microweber/Controllers/ModuleController.php#L45) and post the result here

**Comment by chlarsen** [comment]
Thanks a lot, Peter. Unless you note sth obvious with the output below, I will set up a separate sandbox for you to play with...
Here is the output of ''dd($_REQUEST) added - the information returned changes depending on the site, of course, but the output looks half-way logical.
Example, from '''https://www.caocuero.com/admin/view:shop/action:orders#orderstype=completed'' I get:
```
array:6 [▼
  "data-type" => "shop/orders"
  "data-parent-module-id" => "mw-main-module-backend"
  "data-parent-module" => "shop"
  "id" => "mw-admin-manage-orders-list"
  "class" => " module module-shop-orders "
  "order-type" => "completed"
]
```
Or this from ''https://www.caocuero.com/admin/view:content/action:posts'':
```
array:4 [▼
  "module" => "content/manager"
  "skip-static-pages" => "true"
  "is_shop" => "n"
  "id" => "pages_edit_container"
]
```
Adding dd($_SERVER) instead yields, when calling ''https://www.caocuero.com/admin/view:shop'':
```
array:41 [▼
  "HOME" => "/nonexistent"
  "USER" => "microweber.caocuero.com"
  "FCGI_ROLE" => "RESPONDER"
  "SCRIPT_FILENAME" => "/home/www_php/caocuero.com/microweber/index.php"
  "QUERY_STRING" => ""
  "REQUEST_METHOD" => "POST"
  "CONTENT_TYPE" => "application/x-www-form-urlencoded; charset=UTF-8"
  "CONTENT_LENGTH" => "58"
  "SCRIPT_NAME" => "/index.php"
  "REQUEST_URI" => "/module/"
  "DOCUMENT_URI" => "/index.php"
  "DOCUMENT_ROOT" => "/home/www_php/caocuero.com/microweber"
  "SERVER_PROTOCOL" => "HTTP/1.0"
  "HTTPS" => "on"
  "GATEWAY_INTERFACE" => "CGI/1.1"
  "SERVER_SOFTWARE" => "nginx/1.9.12"
  "REMOTE_ADDR" => "113.162.125.231"
  "REMOTE_PORT" => ""
  "SERVER_ADDR" => "127.0.1.106"
  "SERVER_PORT" => "10007"
  "SERVER_NAME" => "www.caocuero.com"
  "REDIRECT_STATUS" => "200"
  "HTTP_HOST" => "www.caocuero.com"
  "HTTP_X_REAL_IP" => "113.162.125.231"
  "HTTP_X_FORWARDED_FOR" => "113.162.125.231"
  "HTTP_X_FORWARDED_PROTOCOL" => "https"
  "HTTP_X_HOST" => "www.caocuero.com"
  "HTTP_CONNECTION" => "close"
  "HTTP_CONTENT_LENGTH" => "58"
  "HTTP_USER_AGENT" => "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
  "HTTP_ACCEPT" => "*/*"
  "HTTP_ACCEPT_LANGUAGE" => "en-US,en;q=0.5"
  "HTTP_ACCEPT_ENCODING" => "gzip, deflate, br"
  "HTTP_DNT" => "1"
  "HTTP_CONTENT_TYPE" => "application/x-www-form-urlencoded; charset=UTF-8"
  "HTTP_X_REQUESTED_WITH" => "XMLHttpRequest"
  "HTTP_REFERER" => "https://www.caocuero.com/admin/view:shop"
  "HTTP_COOKIE" => "back_to_admin=https%3A//www.caocuero.com/admin/view%3Ashop; laravel_session=eyJpdiI6IktadnNLUmo3bTZYSkVhU1dTZDNJeWc9PSIsInZhbHVlIjoiQ0Y0M0ljcDh1RjVZQU1kQVVkMU9YbUVWNXRuS3hoUWxkR3U2NzZcL3czeER3U0xPZHllWG4yRTJnRGk4ZlR6Ykg1XC9qQ1NOMGJhSFR6alNKNnBBXC9MU0E9PSIsIm1hYyI6ImE0MjNjOTY0NjViMjEzM2NiNDQzMzI3OTg4ZmJlNWVjYWIwNDkzNzBkYmViY2YzNTFiZDYzYmQwYWEwY2JmODUifQ%3D%3D"
  "PHP_SELF" => "/index.php"
  "REQUEST_TIME_FLOAT" => 1458783518.5699
  "REQUEST_TIME" => 1458783518'':
]
```
Or from ''https://www.caocuero.com/admin/view:content'':
```
array:41 [▼
  "HOME" => "/nonexistent"
  "USER" => "microweber.caocuero.com"
  "FCGI_ROLE" => "RESPONDER"
  "SCRIPT_FILENAME" => "/home/www_php/caocuero.com/microweber/index.php"
  "QUERY_STRING" => ""
  "REQUEST_METHOD" => "POST"
  "CONTENT_TYPE" => "application/x-www-form-urlencoded; charset=UTF-8"
  "CONTENT_LENGTH" => "48"
  "SCRIPT_NAME" => "/index.php"
  "REQUEST_URI" => "/module/"
  "DOCUMENT_URI" => "/index.php"
  "DOCUMENT_ROOT" => "/home/www_php/caocuero.com/microweber"
  "SERVER_PROTOCOL" => "HTTP/1.0"
  "HTTPS" => "on"
  "GATEWAY_INTERFACE" => "CGI/1.1"
  "SERVER_SOFTWARE" => "nginx/1.9.12"
  "REMOTE_ADDR" => "113.162.125.231"
  "REMOTE_PORT" => ""
  "SERVER_ADDR" => "127.0.1.106"
  "SERVER_PORT" => "10007"
  "SERVER_NAME" => "www.caocuero.com"
  "REDIRECT_STATUS" => "200"
  "HTTP_HOST" => "www.caocuero.com"
  "HTTP_X_REAL_IP" => "113.162.125.231"
  "HTTP_X_FORWARDED_FOR" => "113.162.125.231"
  "HTTP_X_FORWARDED_PROTOCOL" => "https"
  "HTTP_X_HOST" => "www.caocuero.com"
  "HTTP_CONNECTION" => "close"
  "HTTP_CONTENT_LENGTH" => "48"
  "HTTP_USER_AGENT" => "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
  "HTTP_ACCEPT" => "*/*"
  "HTTP_ACCEPT_LANGUAGE" => "en-US,en;q=0.5"
  "HTTP_ACCEPT_ENCODING" => "gzip, deflate, br"
  "HTTP_DNT" => "1"
  "HTTP_CONTENT_TYPE" => "application/x-www-form-urlencoded; charset=UTF-8"
  "HTTP_X_REQUESTED_WITH" => "XMLHttpRequest"
  "HTTP_REFERER" => "https://www.caocuero.com/admin/view:content"
  "HTTP_COOKIE" => "back_to_admin=https%3A//www.caocuero.com/admin/view%3Acontent; laravel_session=eyJpdiI6Ik52TDU2TGFTT1ozcmduc0crRGhGNGc9PSIsInZhbHVlIjoiaDFUaThFcFVuWG1qU09XV3dIQUZqbGJ3anVpazkrUUVyaTRPSFplVEQ5dHFpY1wvK09qSkpIMFZwYW5QY3RvN1luQkhVeHd6QmRcLzJ0SWJvemtTa1ozZz09IiwibWFjIjoiZDhmMjAyNzc5YTNjNmRlNGM1Y2Y5Yjk1ZjE0MzMzYWU2N2JkMzA2ZTA5NDc5YzA0MmI0MTg4MDE4MzA2YzgwMiJ9"
  "PHP_SELF" => "/index.php"
  "REQUEST_TIME_FLOAT" => 1458783623.8415
  "REQUEST_TIME" => 1458783623
]
```
Does this help???
Thank you so much,
Chris

**Comment by chlarsen** [comment]
Peter, I have created the sandbox. What is your e-mail address?
Thanks!
C.

**Comment by ash-rain** [comment]
Hi, you can use peter /at microweber.com :) I suspect there might be some PostgreSQL-specific issues with the current DB layer code. I have to further investigate, but can you confirm adding a table prefix gets you through install?

**Comment by peter-mw** [comment]
Maybe its fixed, it was because of the port

Can you update your install

Just replace the "src" folder with the one from the zip https://github.com/microweber/dist/raw/master/microweber-update.zip

**Comment by peter-mw** [comment]
its fixed, to be verified and closed 

/ping @chlarsen

**Comment by chlarsen** [comment]
Thank you so much, Peter. Hugely appreciated. Proxy caching via Nginx as 
well as FastCGI caching do work, too.
