### ISSUE TITLE
Cannot upload

### ISSUE THREAD

**Issue by chlarsen** [microweber/microweber#347]
I get this (see screenshot) whenever I try to upload a file. Permissions seem to be alright - any ideas? Debug and logs do not yield anything :-(
Thank you so much!
Chris
![screenshot from 2016-03-21 19 34 52](https://cloud.githubusercontent.com/assets/2879565/13919091/0780d08c-ef9e-11e5-8203-e7a50fb37e9b.png)

**Comment by peter-mw** [comment]
This is related do your Nginx issue #345

**Comment by chlarsen** [comment]
Thanks a lot Peter. What is confusing: I have been able to solve my Nginx issue by simply having Nginx with FastCGI run in SSL mode, and the reverse Nginx proxy nor the browser do not complain anymore. So I naively thoght, the Nginx issue got at least a doable workaround...?

**Comment by peter-mw** [comment]
there are some Nginx rewrite rules which may be useful

https://www.rosehosting.com/blog/install-microweber-ubuntu-14-04/

can you see if you can make it work with them

**Comment by peter-mw** [comment]
@chlarsen I might have fixed it

Can you update your install

Just replace the "src" folder with the one from the zip https://github.com/microweber/dist/raw/master/microweber-update.zip

**Comment by chlarsen** [comment]
Dear Peter,
I have replaced the /src folder with the update, but, alas, the error continues. Just to recapitulate: I am running my instance (as well as the sandbox) with PostgreSQL (with prefix, which makes the installation complete without any errors) and continue to get this error in my Nginx access log, as mentioned before in https://github.com/microweber/microweber/issues/345:
````
From: 113.162.125.233 | Time: 25/Mar/2016:03:26:39 +0100 | Cache status: - | Cache control: - | Cache expires: - | Request: GET /userfiles/modules/microweber/api/editor_externals.js?mwv=1.0.7&_=1458872799026 HTTP/1.0 | Status: 200 | Body sent: 105b | Requested: 1190b | Total sent: 343b | Referrer: https://www.caocuero.com/editor_tools/plupload?type=explorer&filters=png,gif,jpg,jpeg,tiff,bmp,svg&multiple=true&autostart=undefined&mwv=1.0.7 | User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36 | Request time: 0.000ms | Compression: - 
From: 113.162.125.233 | Time: 25/Mar/2016:03:26:39 +0100 | Cache status: - | Cache control: - | Cache expires: - | Request: GET /userfiles/modules/microweber/api/editor_externals.js?mwv=1.0.7&_=1458872799130 HTTP/1.0 | Status: 200 | Body sent: 105b | Requested: 1235b | Total sent: 343b | Referrer: https://www.caocuero.com/editor_tools/wysiwyg?content_id=1&content_type=page&subtype=static&parent_page=0&inherit_template_from=0&live_edit=true&preview_template=&preview_layout=index.php | User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36 | Request time: 0.000ms | Compression: - 
````
Specifically, the referrer URLs  https://www.caocuero.com/editor_tools/plupload?type=explorer&filters=png,gif,jpg,jpeg,tiff,bmp,svg&multiple=true&autostart=undefined&mwv=1.0.7 and https://www.caocuero.com/editor_tools/wysiwyg?content_id=1&content_type=page&subtype=static&parent_page=0&inherit_template_from=0&live_edit=true&preview_template=&preview_layout=index.php do not exist. There is not "microweber/editor_tools/" directory anywhere.

**Comment by chlarsen** [comment]
Fixed , as the underlying bug got ironed out here:  Microweber in FreeBSD jail with PHP-FPM and Nginx in FastCGI mode behind Nginx reverse proxy in different jail #345.
Thanks a lot!
Chris
