### ISSUE TITLE
Requirement list incomplete

### ISSUE THREAD

**Issue by jurchiks** [microweber/microweber#348]
Your requirement list in the README shows only a couple of PHP requirements, but what about all the Bower/Gulp/NPM stuff?
Obviously, for just running it, PHP is enough, but I will probably have to make my own design and add some functionality, so I would like to know what exactly I will need to achieve this.

**Comment by ash-rain** [comment]
The list is comprehensive - it's a list of requirements.
You may choose any development tools of your preference, but we don't compile core assets and so on. You just need composer for dependencies.

**Comment by jurchiks** [comment]
Then what's with the following files:
bower.json
gulpfile.js
package.json
?

**Comment by ash-rain** [comment]
These are part of Laravel

**Comment by jurchiks** [comment]
https://github.com/laravel/laravel/tree/5.1
bower.json does not exist (same for 5.0)
gulpfile.js contents are quite different: https://github.com/laravel/laravel/blob/master/gulpfile.js
package.json contents are also different

**Comment by ash-rain** [comment]
See development branches to find the preferred Laravel version. We try to keep "inherent" files as close to the Laravel master as possible, for developers' sake, but you should expect minor differences. Feel free to modify them as you see fit, they have no direct relation to Microweber code.

**Comment by jurchiks** [comment]
So they don't actually matter for this project?

**Comment by ash-rain** [comment]
Depends on what you mean exactly, but you can delete them and everything will still work. I hope that answers the question.

**Comment by jurchiks** [comment]
Yep, that's what I meant.
Is it a weird design decision on Laravel's part to include those files or is it that this project actually deleted the dependencies on those files/isn't relying on them?

**Comment by ash-rain** [comment]
We're planning some changes in that regard, since right now things aren't exactly where we want them, with regard to your comment, but for the record they serve a "bootstrapping" purpose, since many developers usually create some of these files anyway.

**Comment by peter-mw** [comment]
hi @jurchiks 

those files are not really used, its safe to be deleted. 

they left from earlier laravel version https://github.com/laravel/laravel/tree/5.0

**Comment by jurchiks** [comment]
So you do not use any JS package managers or CSS precompilers or anything like that?

**Comment by peter-mw** [comment]
nothing else besides composer for the PHP packages

**Comment by jurchiks** [comment]
Ok, then I'm closing this issue.
