### ISSUE TITLE
Registration e-mail text cannot be edited

### ISSUE THREAD

**Issue by jurchiks** [microweber/microweber#349]
http://snag.gy/hlwo2.jpg
This should definitely be editable here.
Also, the subject input is way too small, width: 100% would be much better and more suitable to most people.

**Comment by peter-mw** [comment]
Strange, you are experiencing similar issue to #347

Do you use Nginx?

**Comment by jurchiks** [comment]
No, I used the built-in PHP server.

**Comment by peter-mw** [comment]
Wow i didnt event knew it works under the built-in php  server

Can you paste the command you use to start it.

**Comment by jurchiks** [comment]
`php -S localhost:8080` (or w/e other port you want)

**Comment by ash-rain** [comment]
Dude WHY? :laughing: You won't be able to serve Microweber like this, you need a bit more advanced server for that.

**Comment by jurchiks** [comment]
Dude, to test it out!

**Comment by peter-mw** [comment]
i will take a look and try to fix it. 

in meantime you cant test at http://demo.microweber.org

**Comment by ash-rain** [comment]
Sorry, it's cool you're trying but I don't think it's wise. That thing is not reliable.

**Comment by jurchiks** [comment]
Ok, thx :)

I also noticed a weird thing - when you're running it from the built-in server, you can not view the website in non-live edit mode without logging out of your admin account.
If you click on "View Website" in the Live edit menu, it redirects you to about:blank.
Perhaps some $_SERVER variables are missing, although that shouldn't be the case since you should be using relative URLs anyway.

**Comment by jurchiks** [comment]
@ash-rain sorry, I don't really care. "That thing" can run all the sites I've had to work with.

**Comment by ash-rain** [comment]
Possibly there are even more issues. It may be worth looking into, but don't rely on support for now. You can pick any of the options we've listed in the docs - IIS, nginx and Apache are generally supported.
It's totally up to you what technology stack you use, I'm just saying we haven't considered it for testing so far and you should be prepared for surprises if you go with the built-in server.
Cheers

**Comment by peter-mw** [comment]
there are more issues yes. the image upload, etc
![image](https://cloud.githubusercontent.com/assets/5698247/14027092/a73ebe9c-f1fe-11e5-927f-c1655766f313.png)

do you know if the build in server reads the htaccess by some means.... i am surpised that the url rewrite works to some extent

**Comment by jurchiks** [comment]
@ash-rain That's better. Thanks!

@peter-mw ah yeah, it doesn't read .htaccess... But then again, neither does nginx.
Well, I guess I'll have to try on Apache then.

**Comment by peter-mw** [comment]
i found the bug, its because of the port 8080, fixing it now

**Comment by jurchiks** [comment]
lolwhat? For real?

**Comment by peter-mw** [comment]
I may have fixed it 

Can you update your install

Just replace the "src" folder with the one from the zip https://github.com/microweber/dist/raw/master/microweber-update.zip

**Comment by peter-mw** [comment]
@jurchiks let me know if it works

i am pleasantry surprised that it works on the build in server it seems its pretty fast

**Comment by jurchiks** [comment]
Yep, works :)

**Comment by jurchiks** [comment]
Hmm, weird thing: I opened checkout and am trying to edit the custom fields, but they don't actually seem to save.

To be exact:
1) the `Personal Information` block does not even show any `Settings` options at all
2) when I open the Settings panel for Address, which is a custom field, and uncheck `State/Province`, then close the dialog - the content does not update, and refreshing the page doesn't do it either. I open up the same Settings panel again, and the `State/Province` is unchecked, but it is still shown.
The AJAX request definitely does not include the `state` field, so I believe it could be that the backend does not check for fields that exist in database but don't exist in the request `options` list.

**Comment by peter-mw** [comment]
i see it, yes can you open separate issue
