### ISSUE TITLE
Contact form and Test email gives error 500

### ISSUE THREAD

**Issue by nickwuk** [microweber/microweber#365]
I'm using version 1.0.7 and I'm getting error 500 when submitting the contact form or test email (in settings). I see in userfiles/modules/settings/group/email.php there is a reference to api_html/Microweber/Utils/MailSender/test the closest I can find to this is /src/Microweber/Utils/MailSender.php

**Comment by peter-mw** [comment]
hi nick, have you setted up the email settings?

**Comment by nickwuk** [comment]
Hi Peter,
I've enabled debugging by renaming the .env.example file to .env but nothing happens when I submit the contact form, and no error messages. I’ve not setup SMTP settings, instead it’s set to use PHP mail function. 
![email-sending](https://cloud.githubusercontent.com/assets/7723418/16424944/175ae48e-3d5a-11e6-9c13-de39cf7e71a5.jpg)

**Comment by peter-mw** [comment]
hi nick,

can you put 

`debug=true` in the .env file and delete anything else in it 

try to get the response from the network tab, not from the console

![image](https://cloud.githubusercontent.com/assets/5698247/16451030/23dc9fe0-3e09-11e6-9f53-237abd8fa196.png)

**Comment by nickwuk** [comment]
Hi Peter,

The responce for test just says "Woops, looks like something went wrong."
![contact-form-network-test-responce](https://cloud.githubusercontent.com/assets/7723418/16503823/c3281576-3f0c-11e6-8449-78c2bafec559.jpg)

**Comment by peter-mw** [comment]
Ni nick,

please turn on debug mode from this line https://github.com/microweber/microweber/blob/master/config/app.php#L16

make it

`'debug' => true`

and run the email again, it should show the error

**Comment by nickwuk** [comment]
Hi Peter,

I've done that and Chrome's Inspector now shows the error as:

"escapeshellarg() has been disabled for security reasons"

So it looks like this php function is disabled on the web server.

**Comment by nickwuk** [comment]
Hi Peter,

I've enabled escapeshellarg() on the server and it's now working.

Many thanks,
Nick

**Comment by peter-mw** [comment]
hi nick, 

i didnt know that `escapeshellarg` is required to send email. probably the laravel email function is using it somewhere 

im glad it works now
