### ISSUE TITLE
PDOException

### ISSUE THREAD

**Issue by kukujiabo** [microweber/microweber#368]
production.ERROR: exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'microweb.local_modules.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by' in /Users/merocchen/merocZone/project/php/microweber/vendor/laravel/framework/src/Illuminate/Database/Connection.php:319

I encounter this problem while installing, and I wonder if it is my mysql 5.6 version problem. But it's more like to be a sql problem. I want some help.

**Comment by peter-mw** [comment]
strange, seems you have `sql_mode=only_full_group_by` setting in the mysql config 

You can try to disable it: http://stackoverflow.com/questions/23921117/disable-only-full-group-by

did you set this setting or it comes by default?

**Comment by plasebo** [comment]
@peter-mw : Have this issue been solve in version 1.1.3

I'm currently using version 0.951, yeah old version and the website has been running smoothly for 5 years now. Unfortunately, recently, when i login to the admin, the error quoted by kukujiabo appears and the whole website is no more working, both the frontend and the admin report this error.

To solve this issue, I'm restoring a backup, for now I can't update the website through the admin.

Do you have a solution to bypass this issue on version 0.951?

Thanks in advance

**Comment by plasebo** [comment]
@peter-mw : I can't modify the sql_mode=only_full_group_by setting in phpmyadmin since I'm using a shared hosting...

**Comment by peter-mw** [comment]
hi @plasebo this issue is resolved in the newer versions of the CMS

im afraid your version is very old and you will not be able to update , you can ask your hosting provider if they have solution
