### ISSUE TITLE
url wrong

### ISSUE THREAD

**Issue by PowerChaos** [microweber/microweber#374]
hi,
when i type in domain.com/admin i get the following url
would be nice to have that fixed

domain.com/home/domain/public_html/admin/

this only happends if i type in with out a end slash , but i do not like it to have my root dir visible in my url xD

Greets From PowerChaos

**Comment by peter-mw** [comment]
hi, can you tell us how you end up with this url?

**Comment by PowerChaos** [comment]
hi,
if i put the script in a subfolder then it does work normal
but on the root it does not

https://www.manuagere.be 
feel free to test it out :sweat_smile: 
but let me know when ready as i am using that domain for a lot of testings :smiling_imp: 

i use google chrome

to explain the setup easy
the domain with www is hosted on a vps (cpanel  and www act as subdomain )  ,
www and non www got differend adresses/locations 
but that doesnt mather xD
also https is forced

i use apache created with easy_apache4 ( cpanel ) so it should be apache 2.4
i only changed the .htaccess to include

```
  # /* force redirect to https */
 RewriteCond %{HTTPS} off
 RewriteRule (.*) https://%{SERVER_NAME}/$1 [R,L]
 # /* End Force HTTPS */ 
```

all other things are just basic

also i can not edit my header , it got a overflow of the edit bar :confused: 

Greets From PowerChaos

**Comment by peter-mw** [comment]
Hi, i was able to login at the address https://www.manuagere.be/admin/

No subfolder appears to me? Can you post screenshot of where does it appear? 


for the header edit overflow bug - this is fixed, you need to update this file https://github.com/microweber/microweber/blob/1.0.8/userfiles/modules/microweber/css/liveedit.css

**Comment by PowerChaos** [comment]
ok thank you,
i figured the problem out
seems google chrome is doing silly 
even in incognito it was doing silly ( i use incognito instead clearing cache ) 

as i use that website for other scripts and testing (was also a bug on other script  and reported there by many users) dit chrome cached the url redirect ? (even on incognito ) 

i tried it couple of times ( even now it still does it ) 
but it doesnt do it anymore in incognito mode
so my guess is that it is google chrome cache is doing strange

the thing it was doing is if you do not use a traling slash on the end , it will redirect to the relative path ( like /home/user/www ) with the message that the page is not found ( basicly the homepage )

sorry for the trouble and thank you for your support and fast response :smiley:
