### ISSUE TITLE
Products by category (feature request)

### ISSUE THREAD

**Issue by nickwuk** [microweber/microweber#381]
Unless I've missed something I can't see any way to show a sub-set of products, or just one product on a page. It would be great if the products module could be extended with a facility to individually select the products to show, or to select by category, so that different products could be shown on different product category pages.

**Comment by peter-mw** [comment]
hi, it has such option in the 1.0.8 branch 

![image](https://cloud.githubusercontent.com/assets/5698247/20751766/5372518e-b706-11e6-95d3-86eb01004591.png)


you can install version 1.0.8 with 

`composer create-project microweber/microweber my_site 1.0.8.x-dev --prefer-dist --no-dev --no-plugins --no-scripts --ignore-platform-reqs`

**Comment by nickwuk** [comment]
Having updated to 1.0.8 the option to 'Show only from category' now shows
once the 'Shop' page is selected in the 'Display post from page' dropdown.

 

  _____
