### ISSUE TITLE
Parse error in auth.php

### ISSUE THREAD

**Issue by nickwuk** [microweber/microweber#382]
Downloaded v1.0.8 today and tried loading on local XAMPP webserver to install but get the following parse error:

syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in D:\www\mw108\config\auth.php on line 62

Line 62 is:
'model' => App\User::class,

v1.0.8 has:
'model' => 'App\User',

**Comment by peter-mw** [comment]
hi, what php version you have on xampp?

**Comment by nickwuk** [comment]
Php5.4.39

 

(Trying to add Php7)

 

  _____

**Comment by peter-mw** [comment]
you need at least PHP 5.6 for version 1.0.8

**Comment by nickwuk** [comment]
I've updated to XAMPP 5.6.28 using Php 5.6.28, so the v1.0.8 install has now
worked.

 

Could the install be extended perhaps to check the pre-requisite Php
version?

 

This issue was due to me trying to install with an older version of Php so
I'll close the issue.

 

  _____
