### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by iboldurev** [microweber/microweber#384]
Hi

Please tell me how to translate the menu list into other languages, as well as the name of a product in a store

**Comment by peter-mw** [comment]
hi, multilingual support is not implemented yet

**Comment by Staalkoper** [comment]
He's in luck if he means to change the site language, as you've already added this feature.
Settings -> Language -> "Website Language"

If your language is not attached you can translate it right there :)

> as well as the name of a product in a store

If you mean that you want the change the product name title then it's easy - It's the same place as when you added the product and added a title for it.

**Comment by iboldurev** [comment]
write more

For example I have a website in 2 languages

There is 1 product called (Russian Product)

How do I switch the site into another language and change the name of the instance on the english version
