### ISSUE TITLE
Delivery Gateway

### ISSUE THREAD

**Issue by iboldurev** [microweber/microweber#385]
Hi

In the system, there are several possible methods of payment, as well as through the implementation of such a delivery methods

Example (Implemented)

![img](https://cloud.githubusercontent.com/assets/17103170/21343000/5d3bb268-c69d-11e6-8c7d-7800262ef8ef.png)

**Comment by peter-mw** [comment]
hi, we have plans to add this functionality, but i cannot give you ETA on it , if you wish to help you can sent pull request :)
