### ISSUE TITLE
Category Pages not loading via category module links

### ISSUE THREAD

**Issue by nickwuk** [microweber/microweber#396]
I've read the instructions for categories [here](https://microweber.com/creating-a-new-category) and it says: "_Clicking on it [a category link] redirects to its interface. There you can include anything you wish – pictures, videos, text fields, contact fields, the whole range of different Modules and Layouts._" But, after adding the categories module to a page, clicking on a category link in either 1.0.7 or 1.0.8 doesn't seem to do anything. Even if I upload an image to the gallery under the Picture Gallery tab, there is no response when the category link is clicked.

Maybe categories only apply to products and blogs? Maybe I should be using the 'Pages Menu' module.

**Comment by peter-mw** [comment]
hi @nickwuk ,

i will include this module in the 1.0.8 and fix this issue

**Comment by peter-mw** [comment]
i will investigate this and try to fix it

**Comment by nickwuk** [comment]
Category links re-checked in 1.0.9 and are now working.
