### ISSUE TITLE
Calendar Module (question)

### ISSUE THREAD

**Issue by nickwuk** [microweber/microweber#397]
I'm trying to create a calendar module and need the module install to create a new database table. The $config['tables'] parameter in the module config.php file allows the table name, field names, and field types to be defined in an array, which function _exec_table_builder in Providers\Database\Utils.php processes to create the table and fields. Is there a way to define field lengths, auto-increment, and indexes?

**Comment by peter-mw** [comment]
You can define tables as here https://github.com/microweber/microweber/blob/1.0.8/userfiles/modules/testimonials/config.php#L11-L36

the Schema types are mapped to Laravel's https://laravel.com/docs/5.0/schema#adding-columns 

After you modify the `$config['tables'] ` array, you must reload the modules from Admin -> Settings -> Reload Modules

**Comment by nickwuk** [comment]
Thanks for the links and info Peter. Yes I was using the testimonials module as a template. I tried specifying 'varchar' in the tables array for field type but then only the id field was created.  Also tried 'char' and 'time' but the presence of any of these seems to stop the field creation at the id field. So the field types 'integer' and 'text' seem to work, but maybe none of the others?

**Comment by nickwuk** [comment]
My plan is to create a module using the FullCalendar CRUD from [here](https://www.jqueryajaxphp.com/fullcalendar-crud-with-jquery-and-php/) and I got as far as installing the module in MW v1.0.8 but was getting several json console errors. So I've replaced the CRUD jquery with the  jquery from the standard FullCalendar demo (both CRUD and standard demo tested as working outside MW). Without the CRUD jquery the calendar does display in the live edit popup, but without events. I see in the console that there are 2 errors, the first is "Uncaught TypeError: a.toLowerCase is not a function", but there are no errors when tested outside MW.

Standard FullCalendar in Live Edit:

![calendar-module-2](https://cloud.githubusercontent.com/assets/7723418/22019977/c58162de-dcad-11e6-9636-8ad0b91c0f54.jpg)

Console Errors:

![calendar-module-error1](https://cloud.githubusercontent.com/assets/7723418/22020007/e4463c62-dcad-11e6-99ee-eb31d8a994dc.jpg)

**Comment by peter-mw** [comment]
hi nick,

you do not need to load jquery at all, its loaded automatically in admin and frontend 

can you remove the jquery

**Comment by nickwuk** [comment]
I started without jquery, I've now removed jquery.js, so within script tags in admin.php I now have:
`	mw.require("<?php print $config['url_to_module'];?>css/fullcalendar.css", true);
	mw.require("<?php print $config['url_to_module'];?>moment.min.js", true);
	mw.require("<?php print $config['url_to_module'];?>jquery-ui.js");
	mw.require("<?php print $config['url_to_module'];?>fullcalendar.js", true);`
But still get the same error.

**Comment by peter-mw** [comment]
seems its jquery-ui problem

can you remove mw.require("<?php print $config['url_to_module'];?>jquery-ui.js");

and put 

`mw.lib.require('jqueryui')`

**Comment by nickwuk** [comment]
I've replaced with the above, refreshed the modules, refreshed the page, but same error occurs (same in Firebug too).

**Comment by peter-mw** [comment]
hi,

i just made it work on my end


here is the code

```


<script>
    mw.lib.require('jquery-ui');
</script>
<script>
     mw.require("<?php print $config['url_to_module'];?>fullcalendar-3.1.0/fullcalendar.min.css");
     mw.require("<?php print $config['url_to_module'];?>fullcalendar-3.1.0/lib/moment.min.js");
     mw.require("<?php print $config['url_to_module'];?>fullcalendar-3.1.0/fullcalendar.js");

</script>

<script>

    $(document).ready(function() {

        $('#calendar').fullCalendar({
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'month,agendaWeek,agendaDay,listWeek'
            },
            defaultDate: '2016-12-12',
            navLinks: true, // can click day/week names to navigate views
            editable: true,
            eventLimit: true, // allow "more" link when too many events
            events: [
                {
                    title: 'All Day Event',
                    start: '2016-12-01'
                },
                {
                    title: 'Long Event',
                    start: '2016-12-07',
                    end: '2016-12-10'
                },
                {
                    id: 999,
                    title: 'Repeating Event',
                    start: '2016-12-09T16:00:00'
                },
                {
                    id: 999,
                    title: 'Repeating Event',
                    start: '2016-12-16T16:00:00'
                },
                {
                    title: 'Conference',
                    start: '2016-12-11',
                    end: '2016-12-13'
                },
                {
                    title: 'Meeting',
                    start: '2016-12-12T10:30:00',
                    end: '2016-12-12T12:30:00'
                },
                {
                    title: 'Lunch',
                    start: '2016-12-12T12:00:00'
                },
                {
                    title: 'Meeting',
                    start: '2016-12-12T14:30:00'
                },
                {
                    title: 'Happy Hour',
                    start: '2016-12-12T17:30:00'
                },
                {
                    title: 'Dinner',
                    start: '2016-12-12T20:00:00'
                },
                {
                    title: 'Birthday Party',
                    start: '2016-12-13T07:00:00'
                },
                {
                    title: 'Click for Google',
                    url: 'http://google.com/',
                    start: '2016-12-28'
                }
            ]
        });

    });

</script>


<div id='calendar'></div>
```

**Comment by nickwuk** [comment]
Your code in conjunction with using the fullcalendar-3.1.0 folder with all files intact works for me too - brilliant! I retested with my code and it seemed to be the version of moment.min.js causing the error (v2.8.4 in the CRUD download and v2.17.1 in the fullcalendar-3.1.0 download).

Many thanks Peter! I will make the module available when completed.

**Comment by peter-mw** [comment]
great, let me know if you need more help

**Comment by nickwuk** [comment]
In the ajax file called process.php, how can I include/expose the MW functions so that I can run a query like:
 
`$events = mw()->database_manager->query("SELECT * FROM calendar");`

**Comment by peter-mw** [comment]
make a file called `functions.php` , this file is automatically loaded with the website

https://github.com/microweber/microweber/blob/1.0.8/userfiles/modules/testimonials/functions.php#L3-L19

there you can write your functions

for example you can make `save_calendar_event` function and put `api_expose('save_calendar_event');` then your function can be called by ajax on `http://yoursite/api/save_calendar_event`

in javascript you make something like this https://github.com/microweber/microweber/blob/1.0.8/userfiles/modules/testimonials/edit.php#L2-L24 




* NOTE: do not make raw queries like "SELECT * FROM calendar" because the tables may have prefix. Use  [db_get](http://microweber.com/docs/functions/db_get.md) function  or the  [Laravel DB class](
https://laravel.com/docs/5.3/queries#selects) like $query = DB::table('calendar_events')->select('name');

**Comment by nickwuk** [comment]
Thanks Peter for the links and info, I'll need to study those.

I've created a functions.php file and found that the following test correctly populates the calendar:

`<?php
api_expose('get_events');
function get_events($params=array())
{
	$events = array();
		$e = array();
		$e['id'] = "14";
		$e['title'] = "New Event";
		$e['start'] = "2017-01-17T16:00:00+04:00";
		$e['allDay'] = false;
		array_push($events, $e);
	echo json_encode($events);
}
?>`

But if replaced with the following it gives internal server error 500:

`<?php
api_expose('get_events');
function get_events($params=array())
{
    if (is_string($params)) {
        $params = parse_params($params);
    }
    $params['table'] = "calendar";
	$events = db_get($params);
	echo json_encode($events);
}
?>`

It seems that calling db_get causes the error.

**Comment by peter-mw** [comment]
can you enable debug in the config/app.php https://github.com/microweber/microweber/blob/master/config/app.php#L16 , make `'debug' =>true,`

and post the error

**Comment by nickwuk** [comment]
debug is already set to true from the last error tracing. The call to $data = db_get($params) in function get_events() is being called via ajax, the calendar doesn't display, but no errors show. However if I put $data = get_events(); in index.php then the correct data is returned. Is function db_get be available/exposed to be called via ajax using:

`url: '<?php print api_url('get_events'); ?>',`

**Comment by peter-mw** [comment]
Hi Nick,

If you use `api_expose('get_events')` you will make the `get_events` function available at `<?php print api_url('get_events'); ?>` 

You can call the function from any PHP file, and if you need it to be accessible via ajax you just need to expose it with `api_expose`

The `db_get ` is not meant to be exposed by default. You will need to make a "wrapper" function like `get_events` and expose your function.

**Comment by nickwuk** [comment]
Hi Peter,

Assuming there are no other suitable MW functions exposed to the api, I've used the Laravel DB class as you mentioned earlier, and as used in the site_stats module, in the format:

`$data = DB::table('calendar')->select('id','title','startdate','allDay')->get();` 

This now works inside functions.php and the events display in the calendar. I'll update the remaining CRUD functions in a similar way.

Many thanks.

**Comment by nickwuk** [comment]
Almost completed, however I'm having an issue with standard jquery tooltip and dialog styling; Both display text but with none of the standard styling eg borders and backgrounds. The require `mw.lib.require('jquery-ui');` is already present in my code, if I add `mw.require("<?php print $config['url_to_module'];?>fullcalendar-3.1.0/lib/jquery-ui.min.js");` it makes no difference. Any ideas please?

**Comment by peter-mw** [comment]
hi nick,

i found a bug, can you use 

`mw.lib.require('jqueryui') ` without the dash

**Comment by nickwuk** [comment]
Yes that worked :) Thanks!

**Comment by nickwuk** [comment]
The calendar module is completed and tested in Chrome55 but there are two issues in FF & IE:
1) In FF50 dragging the new event to the calendar in admin moves the calendar down the page.
2) In IE11 the calendar module does not display on the website page, no content area outline and no edit controls.

**Comment by nickwuk** [comment]
There's one other issue where the following code causes jquery code to be displayed in the editor in MW v1.0.7 and the 'No posts' message in v1.0.8:

`			eventMouseover: function(event, element) {				
				var tooltip = '<div class="tooltipevent" style="max-width:400px;width:auto;height:auto;background:#eee;position:absolute;z-index:10001;padding:10px 10px 10px 10px;line-height: 150%;">' + event.title + '<br />' + 'date: ' + moment(event.start).format('Do MMM') + '<br />' + 'from: ' + moment(event.start).format('h:mm A') + (event.end == null?'':'<br />' + 'to: ' + moment(event.end).format('h:mm A'))  + (event.description == null?'':'<br />' + event.description) + '</div>';
				$("body").append(tooltip);`

![jquery-with-div-tags-appears-in-editor](https://cloud.githubusercontent.com/assets/7723418/22174138/5af3d6e4-dfce-11e6-9e76-ef1850355d6a.jpg)

If I change the div-tags around the tooltip html to p-tags then all looks good in v1.0.7, the calendar displays.

![ok-with-p-tags-in-1-0-7](https://cloud.githubusercontent.com/assets/7723418/22174145/8ece2762-dfce-11e6-8338-fe5f8c517a96.jpg)

But in v1.0.8 it doesn't show the editor, it only shows the no posts message (works in live edit ok).

![no-posts-v1-0-8](https://cloud.githubusercontent.com/assets/7723418/22174155/c9c0dc48-dfce-11e6-8e76-e02ebe64d8f7.jpg)

**Comment by peter-mw** [comment]
hi nick,

 can you send a zip with the code so we can test locally

**Comment by nickwuk** [comment]
Hi Peter,

This morning I tried adding the admin iframe html into a test.html page and this too confirmed that dragging the new event to the calendar moves the calendar in Firefox but not in Chrome. Tried commenting out js and css but not found the issue. Zip attached.

Many thanks.
[calendar.zip](https://github.com/microweber/microweber/files/723340/calendar.zip)

**Comment by peter-mw** [comment]
seems the jquery draggable is messing with the modal auto-resize, @raikov will try to fix it

**Comment by raikov** [comment]
The problem comes from the **#newevent** element. Its `float` should be removed . Another approach is to set the element to be absolute.

**Comment by nickwuk** [comment]
I've taken out the float and wrapped the `#newevent` in a div with `float` and the dragging is now working.

Brilliant! Just the calendar not appearing in the standard editor is the last issue remaining before the module is hopefully complete.

**Comment by peter-mw** [comment]
hi, the calendar appears ok on my end when viewing post in the admin 

![image](https://cloud.githubusercontent.com/assets/5698247/22207826/5e37fd5a-e189-11e6-89ba-30bf4ee97003.png)


can you tell me how to simulate the issue ?

**Comment by nickwuk** [comment]
Maybe something to do with my installation settings or the Shopmag template because for other pages I see the page without editor, and on mouse hover it darkens and shows a 'Go Live edit' button. For the page with the calendar, if I click the 'Edit page' button, which appears between the search box and 'Go Live edit' button at the top, then I see the same, the area that normally has the editor shows the page with 'Go Live edit' button on mouse hover. So maybe this can be disregarded, I will test in a default install.

![calendar-in-non-live-edit](https://cloud.githubusercontent.com/assets/7723418/22209344/11b9c504-e17e-11e6-9932-61b488d4256a.jpg)

I'll update my repository with the module and submit a pull request (if that's the correct procedure).

**Comment by peter-mw** [comment]
hi nick, you can upload to your fork and submit pull request, then i will merge it

**Comment by nickwuk** [comment]
Hi Peter,

Yes I’ve been trying to do that this morning, but I’m a GitHub newbie struggling 

I’ve setup GitHub Desktop with a repository linked to your MW 1.0.8 which seems to sync ok, and I’ve committed the calendar updates to that repository, but when I try to create a Pull Request the ‘Send Pull Request’ button is greyed out, so I’m searching in Google for answers.

Also setup an online repository at https://github.com/nickwuk/mw1.0.8 which appears to have no files, so I’ve tried creating a second desktop repository in the hope of pushing files to my online repository.

I’ll persevere …

**Comment by nickwuk** [comment]
Pull request now submitted.

**Comment by peter-mw** [comment]
Hi Nick,

Thanks for the pull request and the cool module :) 

Its really useful. 

I will clean it up a bit and merge it

**Comment by nickwuk** [comment]
Hi Peter,

Glad to help in the development of this awesome drag'n drop Website builder! I've learnt a lot about MW module creation, hope my coding follows conventions. Look forward to the next one :)

**Comment by peter-mw** [comment]
thanks :) looking forward for more :)
