### ISSUE TITLE
Possible bug in source code (CWE-480)

### ISSUE THREAD

**Issue by AppChecker** [microweber/microweber#405]
Hello!

We've checked your code with [AppChecker static analyzer](https://cnpo.ru/en/solutions/appchecker.php) and found possible bug:

https://github.com/microweber/microweber/blob/8980e9623bc79b0326073f5e2319d47cf90c5534/userfiles/modules/include/admin.php#L10

```
<input type="text" value="<?php $file; ?>" name="file" class="mw_option_field mw-ui-field w100" id="file" />
```
$file is not displayed. Maybe there should be echo.

Possible defect was found by Echelon Team with [AppChecker static analyzer](https://cnpo.ru/en/solutions/appchecker.php)

**Comment by peter-mw** [comment]
you report is for old version
