### ISSUE TITLE
Products module - select products from category setting (feature request)

### ISSUE THREAD

**Issue by nickwuk** [microweber/microweber#421]
It would be useful in the products module to be able to select a subset of products to display, either by selecting products individually (at first I thought checking the boxes adjacent the products listed might do that but it didn't) or by selecting by category, or both.

In the settings tab there is a 'Display post from page' setting and 'SHOP' is listed, maybe that could be extended to include categories?

**Comment by peter-mw** [comment]
hi Nick,

there is already such setting

![image](https://user-images.githubusercontent.com/5698247/30980092-72a9e894-a488-11e7-8197-951a9254a434.png)

which version are you using?

**Comment by nickwuk** [comment]
Hi Peter,

Ah I see now that 'Display post from page' has to be set to 'SHOP' first and then the 'Show only from category' selection box appears. (I'm working on a 1.0.8 version and comparing to 1.0.9 with latest updates).

Many thanks,
Nick
