### ISSUE TITLE
UPDATE NOT WORKING IN MICROWEBER CMS  (MW HOSTING)

### ISSUE THREAD

**Issue by farabirahmatullah** [microweber/microweber#424]
Hi,
I have newly set up my website with hosting plan from Microweber which offers updated features of microwber cms like new modules and other stuff. I also have a previous website in microweber. But the thing is... even though i click update and system says 'everything is up to date', no new feature is seen there. That means Update is not working.. Can you please check that out...?

**Comment by peter-mw** [comment]
hi, we are working on the auto updates at the moment, will be fixed very soon
