### ISSUE TITLE
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

### ISSUE THREAD

**Issue by ahmadsyamim** [microweber/microweber#431]
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

POST http://localhost/cms/microweber-latest/module/ 500 (Internal Server Error)

  | send | @ | api.6cb3f02e15c27321…67a9dd75.1.0.9.js:6
-- | -- | -- | --
  | ajax | @ | api.6cb3f02e15c27321…67a9dd75.1.0.9.js:6
  | jQuery.ajax | @ | api.6cb3f02e15c27321…a9dd75.1.0.9.js:200
  | r.(anonymous function) | @ | api.6cb3f02e15c27321…67a9dd75.1.0.9.js:6
  | mw._ | @ | api.6cb3f02e15c27321…9dd75.1.0.9.js:1028
  | mw.load_module | @ | api.6cb3f02e15c27321…a9dd75.1.0.9.js:821
  | mw.search | @ | home:139
  | (anonymous) | @ | home:197
  | setTimeout (async) |   |  
  | mw.autocompleteSearch | @ | home:190
  | onkeyup | @ | home:157

**Comment by peter-mw** [comment]
hi @ahmadsyamim, please enable debug in config/app.php and see what is the error

**Comment by ahmadsyamim** [comment]
PDOException in Connection.php line 323:
SQLSTATE[42000]: Syntax error or access violation: 1139 Got error 'this version of PCRE is compiled without UTF support at offset 0' from regexp

QueryException in Connection.php line 647:
SQLSTATE[42000]: Syntax error or access violation: 1139 Got error 'this version of PCRE is compiled without UTF support at offset 0' from regexp (SQL: select `forge_content`.* from `forge_content` where (`title` REGEXP asdasdasdasd or `content_body` REGEXP asdasdasdasd or `content` REGEXP asdasdasdasd or `description` REGEXP asdasdasdasd or `content_meta_keywords` REGEXP asdasdasdasd or `content_meta_title` REGEXP asdasdasdasd or `url` REGEXP asdasdasdasd and `is_active` = 1 and `is_deleted` = 0) and `is_deleted` is not null and `forge_content`.`is_active` = 1 and `forge_content`.`is_deleted` = 0 order by `position` desc limit 5)

**Comment by peter-mw** [comment]
Im seeing this error for 1st time. 

What database are you using and also what is your PHP version?

**Comment by mood48** [comment]
I am getting this error while installing Microweber, I have no idea what could the problem
![error](https://user-images.githubusercontent.com/86103681/164888037-c499d958-61af-473e-adde-8e6fa49fc3ad.png)
