### ISSUE TITLE
Multiple XSS

### ISSUE THREAD

**Issue by thefLink** [microweber/microweber#432]
# Description
Multiple XSS exist in the user information form. The attack payload is executed from username,email,firstname and lastname parameters, due to the lack of encoding for the output documents.

Example attack payload would be:
```
" onmouseover="alert(123)"
```
to be set in the user information as one of these {username,email,firstname,lastname}. 

The XSS then occurs on two different pages:

#### Parameter: email
```
<td title="" onmouseover="alert(123)" style="overflow: hidden; text-overflow: ellipsis; height: 94.9px;"><span class="th-in-td">Email</span>" onmouseover="alert(123)"</td>
```
#### Parameter: Username, email, firstname, lastname,
```
<input class="mw-ui-field" name="username" value="" onmouseover="alert(123)" type="text">
<input class="mw-ui-field" name="email" value="" onmouseover="alert(123)" type="text">
<input class="mw-ui-field" name="first_name" value="" onmouseover="alert(123)" type="text">
<input class="mw-ui-field" name="last_name" value="" onmouseover="alert(123)" type="text">
```

**Comment by peter-mw** [comment]
Hi, all JavaScript is content is removed on saving

Have you tried to save it in the database ? 

I just tried and its not saved. Can you reproduce the `"alert(123)"` after save ?

**Comment by thefLink** [comment]
This javascript is not removed on saving. I am able to spawn the alert() with the steps mentioned above. 
Closing the ticket does not fix the issue

**Comment by peter-mw** [comment]
Hello,

How can i reproduce the bug? Its not showing on my end?

Im trying , but don't see any alert 

![image](https://user-images.githubusercontent.com/5698247/34438631-e4affa12-ecb0-11e7-8cbe-ec067cebf467.png)

**Comment by thefLink** [comment]
Create a new user and then change his nickname to 
```
" onmouseover="alert(123)"
```
Leads to:
````
<input class="mw-ui-field" name="username" value="" onmouseover="alert(123)" type="text">
```
in 
```
/admin/view:modules/load_module:users#edit-user=2
```
