### ISSUE TITLE
Multisite like grav

### ISSUE THREAD

**Issue by arinadi** [microweber/microweber#436]
can microweber multisite for sub domain like grav?
https://learn.getgrav.org/advanced/multisite-setup

**Comment by peter-mw** [comment]
yes. you just need to create a subfolder in the config folder with empty file named `microweber.php`

for example

`config/sub.domain.com/microweber.php`

then you will see the installation screen when you go on the address

**Comment by aneraojunior** [comment]
Hello there. It's not working for me. When i access the subdomain i get a blank page only.
Some idea about what i'm doing wrong?
