### ISSUE TITLE
Payment module radio yes/no setting clears after auto save

### ISSUE THREAD

**Issue by Ezyweb-uk** [microweber/microweber#450]
When the payment module test mode yes/no setting is changed the radio checked status is cleared after the auto save. So for example if test mode 'Yes' or 'No' is clicked the radio is initially checked but after the auto save both radios are unchecked.

**Comment by peter-mw** [comment]
hi nick, for which payment provider is this ?  im just checking but i don't see such bug, or maybe i dont look at the right place

**Comment by Ezyweb-uk** [comment]
Hi Peter, it seems to be the yes/no radios for any payment module, the checked status in the admin popup is cleared after auto-save. I've attached a screen recording.
[Payment-module-yes-no.zip](https://github.com/microweber/microweber/files/2111777/Payment-module-yes-no.zip)

**Comment by peter-mw** [comment]
got it, thanks, we will try to fix it now

**Comment by peter-mw** [comment]
fixed in f81f12ea19db972b9e29a153aa4b65fd282f355a
