### ISSUE TITLE
Content lost during editing and not retrieved with undo

### ISSUE THREAD

**Issue by Ezyweb-uk** [microweber/microweber#454]
Using Bootstrap3 template with v1.1.0, whilst editing content was lost and the undo button did not retrieve it. The following appears in the page code:
`<!-- edit_field_not_found_in_database -->`

And in the database content field:
`<inner-edit-tag>mw_saved_inner_edit_from_parent_edit_field</inner-edit-tag>`

The content that was lost:
`<p class=" element">some text</p>
                        <module class="module module-social-links" data-mw-title="Social Links" id="footer-socials" data-type="social_links" parent-module="social_links" parent-module-id="footer-socials"></module>`

I replaced the content in the database, cleared the cache and reloaded the database in admin, and the the content reappeared. Editing the paragraph element again repeated the issue.

Is it because the p-tag didn't have an id? The content originated from the Bootstrap3 footer template to which I added the 'edit' class.

**Comment by peter-mw** [comment]
ok thats strange, will try this now

**Comment by Ezyweb-uk** [comment]
My template footer.php and style.css are in the attached zip.
[footer.zip](https://github.com/microweber/microweber/files/2144914/footer.zip)

**Comment by peter-mw** [comment]
thanks

**Comment by peter-mw** [comment]
i found the issue

you have put inner edit fields, but seems  you do not have field and rel attributes, 

also on the right div there is edit attribute instead of class 

![image](https://user-images.githubusercontent.com/5698247/42034174-deca9524-7ae7-11e8-928d-f59113513da0.png)

to fix it you must have "rel"  and "field" attributes  on a div that have class 'edit'

**Comment by Ezyweb-uk** [comment]
Ah brilliant, many thanks Peter, I've learn something. I've removed the inner edit class and edit attribute and it seems to be working now.
