### ISSUE TITLE
This $json should be an array

### ISSUE THREAD

**Issue by suxilog** [microweber/microweber#472]
https://github.com/microweber/microweber/blob/6e650af59b96174fd74adc7c2e7756047d2281cd/userfiles/modules/cookie_notice/admin.php#L73

Cause below you use array_merge.

Report again.

**Comment by peter-mw** [comment]
hi, it is array :) 

http://php.net/manual/en/function.json-decode.php

**Comment by suxilog** [comment]
Yes, you are right, it is array.
I mean you may need to add array_wrap() outside the json_decode or check the second argument is not NULL in array_merge() method.

when I browse /admin/view:modules/load_module:cookie_notice first time after installation finished, your project raise 
`(1/1) ErrorException
array_merge(): Argument #2 is not an array`

`at array_merge(array('cookiePolicyURL' => 'privacy-policy', 'showLiveChatMessage' => 'false', 'panelTogglePosition' => 'right', 'unsetDefault' => 'blocked', 'cookies_policy' => 'n', 'Google_Analytics' => array('enabled' => 'false', 'label' => 'Google Analytics', 'code' => 'UA-xxxxxxxxx-1'), 'Tawk.to' => array('enabled' => 'false', 'label' => 'Tawk.to - Live chat', 'code' => ''), 'Smartsupp' => array('enabled' => 'false', 'label' => 'Smartsupp - Live chat', 'code' => ''), 'Hotjar' => array('enabled' => 'false', 'label' => 'Hotjar - Website heatmaps', 'code' => '')), null)
in admin.php line 74`

Maybe you need check here.

**Comment by peter-mw** [comment]
hi @suxilog , can you send a fix ?
