### ISSUE TITLE
Discounts Module

### ISSUE THREAD

**Issue by nerddigestive** [microweber/microweber#487]
Hi,

I know that the discounts module is currently a placeholder, however, you have been promising a working coupon/discount system "soon" for several years now - it would be nice to know when this is actually going to be implemented, since it is a major blocker for our (and many other company's) customers.

Regards,

Ed

**Comment by peter-mw** [comment]
Hi @nerddigestive , we will try to make it faster, but i cant give you ETA of this module.

**Comment by peter-mw** [comment]
this module is included now in the core. its available as of version 1.1.2
