### ISSUE TITLE
microweber.php not created , used Composer Option. Please help to resolve the issue.

### ISSUE THREAD

**Issue by Sudhagar1985** [microweber/microweber#492]
microweber.php not created , installation stopped with the below error. Please Help
Followed the composer install option in the user guide.

Tried with Composer and got the below error, 
[2018-10-04 12:07:32] production.ERROR: Symfony\Component\Console\Exception\RuntimeException: Aborted in D:\microweber\my_site\vendor\symfony\console\Helper\QuestionHelper.php:159
Stack trace:
#0 D:\microweber\my_site\vendor\symfony\console\Helper\QuestionHelper.php(68): Symfony\Component\Console\Helper\QuestionHelper->doAsk(Object(Illuminate\Console\OutputStyle), Object(Symfony\Component\Console\Question\ConfirmationQuestion))
#1 D:\microweber\my_site\vendor\symfony\console\Helper\QuestionHelper.php(415): Symfony\Component\Console\Helper\QuestionHelper->Symfony\Component\Console\Helper\{closure}()
#2 D:\microweber\my_site\vendor\symfony\console\Helper\QuestionHelper.php(71): Symfony\Component\Console\Helper\QuestionHelper->validateAttempts(Object(Closure), Object(Illuminate\Console\OutputStyle), Object(Symfony\Component\Console\Question\ConfirmationQuestion))
#3 D:\microweber\my_site\vendor\symfony\console\Helper\SymfonyQuestionHelper.php(53): Symfony\Component\Console\Helper\QuestionHelper->ask(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle), Object(Symfony\Component\Console\Question\ConfirmationQuestion))
#4 D:\microweber\my_site\vendor\symfony\console\Style\SymfonyStyle.php(294): Symfony\Component\Console\Helper\SymfonyQuestionHelper->ask(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle), Object(Symfony\Component\Console\Question\ConfirmationQuestion))
#5 D:\microweber\my_site\vendor\symfony\console\Style\SymfonyStyle.php(222): Symfony\Component\Console\Style\SymfonyStyle->askQuestion(Object(Symfony\Component\Console\Question\ConfirmationQuestion))
#6 D:\microweber\my_site\vendor\laravel\framework\src\Illuminate\Console\Command.php(298): Symfony\Component\Console\Style\SymfonyStyle->confirm('Do you really w...', false)
#7 D:\microweber\my_site\vendor\laravel\framework\src\Illuminate\Console\ConfirmableTrait.php(31): Illuminate\Console\Command->confirm('Do you really w...')
#8 D:\microweber\my_site\vendor\laravel\framework\src\Illuminate\Foundation\Console\KeyGenerateCommand.php(75): Illuminate\Foundation\Console\KeyGenerateCommand->confirmToProceed()
#9 D:\microweber\my_site\vendor\laravel\framework\src\Illuminate\Foundation\Console\KeyGenerateCommand.php(44): Illuminate\Foundation\Console\KeyGenerateCommand->setKeyInEnvironmentFile('base64:JDupvuxS...')
#10 [internal function]: Illuminate\Foundation\Console\KeyGenerateCommand->fire()
#11 D:\microweber\my_site\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(29): call_user_func_array(Array, Array)
#12 D:\microweber\my_site\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#13 D:\microweber\my_site\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Microweber\LaravelApplication), Array, Object(Closure))
#14 D:\microweber\my_site\vendor\laravel\framework\src\Illuminate\Container\Container.php(539): Illuminate\Container\BoundMethod::call(Object(Microweber\LaravelApplication), Array, Array, NULL)
#15 D:\microweber\my_site\vendor\laravel\framework\src\Illuminate\Console\Command.php(182): Illuminate\Container\Container->call(Array)
#16 D:\microweber\my_site\vendor\symfony\console\Command\Command.php(251): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#17 D:\microweber\my_site\vendor\laravel\framework\src\Illuminate\Console\Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#18 D:\microweber\my_site\vendor\symfony\console\Application.php(946): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 D:\microweber\my_site\vendor\symfony\console\Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Foundation\Console\KeyGenerateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 D:\microweber\my_site\vendor\symfony\console\Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 D:\microweber\my_site\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 D:\microweber\my_site\artisan(33): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 {main}

**Comment by Sudhagar1985** [comment]
Hi , Thanks @peter-mw . It worked. Could you please let me know , Is there any way to integrate user login with Active Directory. For example. I want to authenticate my organization users using the mail id. 
Thanks,
Sudhagar K

**Comment by peter-mw** [comment]
hi, there is a way to make 3rd party login, but you need to do it yourself , check this function https://github.com/microweber/microweber/blob/master/src/Microweber/Providers/UserManager.php#L121

**Comment by Sudhagar1985** [comment]
Thanks it helped.
