### ISSUE TITLE
Still displaying same image after live edit

### ISSUE THREAD

**Issue by jokerlck** [microweber/microweber#500]
Hi,

I am writing my own template and would like to know how to change my background image.
Here is my code.

`<div class="header section edit nodrop safe-mode" style="background-image:url('<?php print template_url('images/'); ?>header.jpg');" rel="global" field="header">`

I want to change the background image to an uploaded image.

image source before live edit: 
    http://_my_site_/userfiles/templates/_my_template_/images/background.jpg
image source after live edit:  
    http://_my_site_/userfiles/media/_my_site_/background.jpg

The background image is still the original one after save and refresh.

I don't know how to get user's uploaded photo.

Many thanks.

**Comment by peter-mw** [comment]
hi, you must put the background on element inside the edit field

its a bug and change background image handle must not appear on .edit 

now the element is on the edit field itself and thats why is not saved

<div class="header section edit nodrop safe-mode"  rel="global" field="header">

<div class="someclass" style="background-image:url('<?php print template_url('images/'); ?>header.jpg');"></div>

</div>

**Comment by jokerlck** [comment]
Here is my code right now.

`
<div class="header-cover section bg-dark-light no-padding edit" rel="global" field="header">
<div class="header section" style="background-image:url('<?php print template_url('images/'); ?>header.jpg'); bottom: 0px;" >
<div class="header-inner section-inner">
<div class="info" style="opcaity: 1;">
<h2 class="title edit" rel="global" field="title"><a>My Title</a></h2>
<h3 class="description edit" rel="global" field="organization">My Organization</h3>
</div>
</div>
</div>
</div>
`

The background element disappear (can't find in google inspect element mode as well).
But it appears again when I remove the `edit` class.

**Comment by peter-mw** [comment]
hi, maybe your previous content is saved in DB

can you try with reset content 

![image](https://user-images.githubusercontent.com/5698247/48436955-c4e96a00-e788-11e8-9804-2e4969d6ac77.png)

**Comment by jokerlck** [comment]
Problem solved. Thank you.
