### ISSUE TITLE
How can I install Microweber on my localhost

### ISSUE THREAD

**Issue by DuynTaDa** [microweber/microweber#509]

**Comment by DuynTaDa** [comment]
I uses Xampp to run projects, so I wanna install mw on the localhost.
After cloning mw, I started xampp and run this url : "localhost/my_microweber/install.php" (my_microweber is my cloned project).
Browser displays "Warning: require(D:\xampp\htdocs\my_microweber\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in D:\xampp\htdocs\my_microweber\bootstrap\autoload.php on line 17"
Thanks for your help ^^

**Comment by peter-mw** [comment]
you need to run `composer install`   or download the zip file from here  https://microweber.com/download

**Comment by DuynTaDa** [comment]
oh thank sir, I succeeded
But why I can't use a cloned mw project?

**Comment by peter-mw** [comment]
from github you need to use `composer` to install the dependent libraries

https://getcomposer.org/download/ 

you clone the repo and then you go in the repo folder and run command `composer install`

**Comment by DuynTaDa** [comment]
ohhh thank sir so much ^^
I understood. I'll try both of way
Thank sir <3
