### ISSUE TITLE
Key of $menu_filter in customed menu skin

### ISSUE THREAD

**Issue by DuynTaDa** [microweber/microweber#512]
hi, I wanna convert dropdown menu to skin of menu in mw

`<ul class="nav navbar-nav navbar-nav-style">
        <li class="nav-item">
                <ul class="dropdown-menu">
                    <li class="dropdown-submenu nav-item">
                        <a class="nav-link" href="/sua-chua-bao-hanh-bao-tri-may-ozone-b964">SỬA CHỮA</a>
                    </li>
                    <li class="dropdown-submenu nav-item">
                        <a class="nav-link" href="/do-kiem-may-ozone-b1066">ĐO KIỂM MÁY OZONE</a>
                    </li>
                </ul>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/tin-tuc">Tin tức</a>
        </li>
    </ul>`

And here is $menu_filter of this menu

`    $menu_filter['ul_class'] = 'nav navbar-nav navbar-nav-style';
    $menu_filter['ul_class_deep'] = 'dropdown-menu';

    $menu_filter['li_class'] = 'nav-item';
    $menu_filter['li_class_deep'] = 'dropdown-submenu nav-item';

    $menu_filter['a_class'] = 'nav-link';
    $menu_filter['I wanna put submenu a class here'] = 'nav-link';`

Plss help me, thanks

**Comment by peter-mw** [comment]
Hello, you can read more about those parameters here http://docs.microweber.com/functions/menu_tree.md

**Comment by DuynTaDa** [comment]
hi Peter, thank for your reply 👍
