### ISSUE TITLE
Hide Recent Orders in dashboard

### ISSUE THREAD

**Issue by layanto** [microweber/microweber#519]
For sites with shop turned off, how can I hide or remove Recent Orders from dashboard?

**Comment by peter-mw** [comment]
ping @PYovchevski , yes, it must be hidden when the shop is off

**Comment by PYovchevski** [comment]
It's done! You will get the fix with the next update ;)

**Comment by layanto** [comment]
Was just about to raise a pull request - check for 'shop_disabled' in 'mw.admin.dashboard.content.2' event bind in microweber/userfiles/modules/shop/functions.php
