### ISSUE TITLE
(1/1) FatalThrowableError Call to undefined method Microweber\Providers\Template::get_stylesheet()

### ISSUE THREAD

**Issue by didoa** [microweber/microweber#548]
After update to Dream template to version 1.4 od microweber stable v. 1.1.5. the whole site firing an exception, the admin still working, so I thing there were some problem in the template itself ... thankx for resolving this quickly.

(1/1) FatalThrowableError
Call to undefined method Microweber\Providers\Template::get_stylesheet()

in header.php line 92
--
at include()in index.php line 14
at include('/nfsmnt/hosting2_2/3/d/3ddc54ca-f26b-4e4e-98f9-e9cd85a3ea62/ekofarma5.com/web/userfiles/templates/dream/index.php')in View.php line 71
at View->__toString()in MicroweberTemplate.php line 46
at MicroweberTemplate->render(array('render_file' => '/nfsmnt/hosting2_2/3/d/3ddc54ca-f26b-4e4e-98f9-e9cd85a3ea62/ekofarma5.com/web/userfiles/templates/dream/index.php', 'page_id' => 1, 'content_id' => 1, 'post_id' => false, 'category_id' => false, 'content' =>array('id' => 1, 'content_type' => 'page', 'subtype' => 'static', 'url' => 'home', 'title' => 'Home', 'parent' => '0', 'description' => null, 'position' => '1', 'content' => null, 'content_body' => null, 'is_active' => '1', 'subtype_value' => null, 'custom_type' => null, 'custom_type_value' => null, 'active_site_template' => 'default', 'layout_file' => 'index.php', 'layout_name' => null, 'layout_style' => null, 'content_filename' => null, 'original_link' => null, 'is_home' => '1', 'is_pinged' => '0', 'is_shop' => '0', 'is_deleted' => '0', 'require_login' => '0', 'status' => null, 'content_meta_title' => null, 'content_meta_keywords' => null, 'session_id' => 'a1XHlulqNzXKMtlneDddK9MHA6ea6YHAuGHLqHyW', 'updated_at' => '2019-03-01 16:54', 'created_at' => '2017-11-28 08:39', 'expires_at' => '0000-00-00 00:00:00', 'created_by' => '1', 'edited_by' => '1', 'posted_at' => '0000-00-00 00:00:00', 'draft_of' => '0', 'copy_of' => '0', 'full_url' => 'https://ekofarma5.com/home', 'render_file' => '/nfsmnt/hosting2_2/3/d/3ddc54ca-f26b-4e4e-98f9-e9cd85a3ea62/ekofarma5.com/web/userfiles/templates/dream/index.php'), 'category' => null, 'page' => array('id' => 1, 'content_type' => 'page', 'subtype' => 'static', 'url' => 'home', 'title' => 'Home', 'parent' => '0', 'description' => null, 'position' => '1', 'content' => null, 'content_body' => null, 'is_active' => '1', 'subtype_value' => null, 'custom_type' => null, 'custom_type_value' => null, 'active_site_template' => 'default', 'layout_file' => 'index.php', 'layout_name' => null, 'layout_style' => null, 'content_filename' => null, 'original_link' => null, 'is_home' => '1', 'is_pinged' => '0', 'is_shop' => '0', 'is_deleted' => '0', 'require_login' => '0', 'status' => null, 'content_meta_title' => null, 'content_meta_keywords' => null, 'session_id' => 'a1XHlulqNzXKMtlneDddK9MHA6ea6YHAuGHLqHyW', 'updated_at' => '2019-03-01 16:54:30', 'created_at' => '2017-11-28 08:39:25', 'expires_at' => '0000-00-00 00:00:00', 'created_by' => '1', 'edited_by' => '1', 'posted_at' => '0000-00-00 00:00:00', 'draft_of' => '0', 'copy_of' => '0', 'full_url' => 'https://ekofarma5.com/home'), 'meta_tags' => true))in Template.php line 199

**Comment by didoa** [comment]
hi, temporarily fixed in header.php by  uncomenting this
`  <link href="{TEMPLATE_URL}assets/dist/main.min.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="{TEMPLATE_URL}assets/css/theme<?php print $color_scheme; ?>.css" id="theme-color" rel="stylesheet" type="text/css" media="all"/>
`
and removing this 
`<link href="<?php print mw()->template->get_stylesheet('assets/less/theme.less','mw-template-dream-style-vars'); ?>" id="theme-style" rel="stylesheet" type="text/css" media="all"/>`

**Comment by peter-mw** [comment]
hi, can you pull from the dev branch

**Comment by The-Steve** [comment]
I faced the same exact error after a fresh installation of MW1.1.6 and update of the Dream Template. 

> hi, can you pull from the dev branch

Newbie on github here. Wondering whether, the whole package need to be pulled and reinstalled or just a select few files that fix the issue. 

Many thanks & Regards.

**Comment by peter-mw** [comment]
hi @The-Steve  and @didoa  , you can download the update files from this repository https://github.com/microweber/update

**Comment by didoa** [comment]
Hi @peter-mw,  it's working,  thank you for support. Didoa
