### ISSUE TITLE
Subscriptions/Recurring Payments 

### ISSUE THREAD

**Issue by fredhampton** [microweber/microweber#558]
Is there a way to have a product in a shop that can be paid for via subscription/Recurring payment ?
We will be selling chocolate and want to offer a way that a members can subscribe so that they can pay each month for new kinds of chocolate to be sent to them.

Thanks !!!

**Comment by peter-mw** [comment]
hello, this function is on the roadmap for future versions, but no work on it has been done yet

**Comment by Ezyweb-uk** [comment]
Peter, I've built a Stripe subscriptions module which I've tested up to MW v1.1.2 and plan to use it for live transactions in the next few weeks; it involves updates to the checkout, custom fields, etc. Maybe I can make it available once tested with the latest MW release.

**Comment by peter-mw** [comment]
hi  @Ezyweb-uk  great news, let us know if works

**Comment by HansSchouten** [comment]
@Ezyweb-uk that would be awesome! I was planning to use Stripe as well.
