### ISSUE TITLE
PHP function finfo_file() maybe disabled

### ISSUE THREAD

**Issue by Ezyweb-uk** [microweber/microweber#590]
PHP function finfo_file() maybe disabled on a shared server for security. I noticed some of the Dream template layout module images were not displaying in the righthand menu, and when I entered one of the image urls into the browser address bar it returned the following fatal error: 

> Call to undefined function Microweber\Utils\lib\PHPImageMagician\finfo_open() 

I've traced this to `$mimeType = finfo_file($finfo, $file);` in file `src\Microweber\Utils\lib\PHPImageMagician\imageLib.php` but also notice the function is referenced in several other files. I've raised this as an issue at [https://github.com/Oberto/php-image-magician/issues/20](https://github.com/Oberto/php-image-magician/issues/20)

**Comment by peter-mw** [comment]
hi @Ezyweb-uk , bug is fixed in the dev branch

**Comment by Ezyweb-uk** [comment]
Thanks Peter, replacing file imageLib.php from the dev branch fixed it. I'll try to remember to check dev first another time :)
