### ISSUE TITLE
v1.1.12 - problem with installing theme update

### ISSUE THREAD

**Issue by didoa** [microweber/microweber#617]
view:settings:1 Uncaught TypeError: mw.install_composer_package_confirm_by_key is not a function
    at HTMLAnchorElement.onclick (VM115 view:settings:1)
onclick @ view:settings:1

![image](https://user-images.githubusercontent.com/32476324/67250626-633b8080-f46c-11e9-935b-6d007154c78d.png)

**Comment by peter-mw** [comment]
Fixed for 1.1.13, you can download the update from here https://github.com/microweber/update
