### ISSUE TITLE
Logo module template setting missing from admin screen

### ISSUE THREAD

**Issue by Ezyweb-uk** [microweber/microweber#625]
In version 1.1.16 the template setting has dissappeared from the admin screen. File userfiles\modules\logo\admin.php includes `<module type="admin/modules/templates" simple=true/>` below the log text field but the template selector does not show.

**Comment by peter-mw** [comment]
Hi @Ezyweb-uk , the header text of the skin was missing, thats why the drop-down was not appearing.  
https://github.com/microweber/microweber/blob/dev/userfiles/modules/logo/templates/default.php#L1-L14

Please add those lines in your skin and it will appear

**Comment by Ezyweb-uk** [comment]
Thanks Peter, confirming I've updated my files and templates now show.
