### ISSUE TITLE
Multilanguage module

### ISSUE THREAD

**Issue by com2** [microweber/microweber#629]
I don't see any documentation so I am just guessing here what this module does. 

Apparently it is possible to add more than one language and configure the default and how languages is detected and switched. There in the administration now appears a manual language switch. 

I had hoped that it would be possible now to translate the page content, but that is apparently not the intention of this module or it is not yet implemented. I switched from one to the other language and the translation is not saved (separately). 

What would be desired is the possiblity to translate content: 

- page content
- page metadata
- menu items
- urls

Would be nice to know where in github this module's official repository can be found. It would allow others to contribute.

**Comment by com2** [comment]
Apparently this module is composer package maintained here: https://github.com/microweber-modules/multilanguage/
I will from now on submit issues there.

**Comment by peter-mw** [comment]
Hello, this module is still in beta and does not work with the current version 1.1.16, if you wish to test it you will need to pull from the dev branch https://github.com/microweber/microweber/tree/dev

**Comment by bobimicroweber** [comment]
Hello @com2

The module is in beta and you can test it on a dev branch.
We work on documentation for multilanguage and we will upload it.
Thank you.
