### ISSUE TITLE
Support for cryptocurrency payments.

### ISSUE THREAD

**Issue by VentGrey** [microweber/microweber#657]
With the advance of technology and businesses starting to accept new ways of payments a module or a payment method for cryptocurrencies like bitcoin, monero, etc might sound like a good idea :)

**Comment by peter-mw** [comment]
good idea, we will think about adding some provider

**Comment by VentGrey** [comment]
Maybe just plain wallet addresses might work. Providers tend to be difficult on some countries and put limitations on retiring.
