### ISSUE TITLE
Template breaks when changing colours

### ISSUE THREAD

**Issue by VentGrey** [microweber/microweber#665]
Using new world, and changed colour to green aside from the default blue colour and breakage happens quickly:

![image](https://user-images.githubusercontent.com/24773698/89091253-d5cb7c00-d36d-11ea-8f79-167052228939.png)

Console shows no special output:

![image](https://user-images.githubusercontent.com/24773698/89091274-f562a480-d36d-11ea-8c62-5e04738b31af.png)

Edit: Tried this in different envirnoments such as online server, local PHP server, apache server, nginx server and the results are the same. Something in the button is corrupting the site.

**Comment by Ertuit** [comment]
> 
> 
> Using new world, and changed colour to green aside from the default blue colour and breakage happens quickly:
> 
> ![image](https://user-images.githubusercontent.com/24773698/89091253-d5cb7c00-d36d-11ea-8f79-167052228939.png)
> 
> Console shows no special output:
> 
> ![image](https://user-images.githubusercontent.com/24773698/89091274-f562a480-d36d-11ea-8c62-5e04738b31af.png)
> 
> Edit: Tried this in different envirnoments such as online server, local PHP server, apache server, nginx server and the results are the same. Something in the button is corrupting the site.

For me, all the template act like that.

**Comment by Ertuit** [comment]
For mee, all the templates act like that.
