### ISSUE TITLE
Module included once in page is executed multiple times

### ISSUE THREAD

**Issue by janbiedermann** [microweber/microweber#681]
Hi,

i created a module and included it once in a page so i would expect it to execute once.
However, when loading the page, the code is executed 4 times, each time completely, with output taken from the last execution.
How come? How to debug?

**Comment by peter-mw** [comment]
Hello , this bug is due to the parser of the page, which is processing the HTML few times. 

We will try to fis this on the new version 1.2 https://github.com/microweber/microweber/tree/1.2

**Comment by janbiedermann** [comment]
Alright, thanks!

**Comment by peter-mw** [comment]
Should be fixed in this commit now https://github.com/microweber/microweber/commit/264b6bcb6b12cf74146b47c9dc19f62cdd36dfa2
