### ISSUE TITLE
Can't change template in 1.2.0-dev1 admin

### ISSUE THREAD

**Issue by Ezyweb-uk** [microweber/microweber#708]
I've manually updated a dev version to 1.2.0-dev1 (on xampp) and updated vendor folder. If I try to change the template in Settings > Templates, I see the preview but the 'Apply this template' button does nothing. There are no laravel errors in storage\logs\laravel.log 

The green 'template settings saved' message does not appear. But it works ok in the latest released 1.2.0 though.

**Comment by peter-mw** [comment]
fixed

**Comment by Ezyweb-uk** [comment]
Thanks Peter, tested as working!
