### ISSUE TITLE
mw_replace_back_this_module errors in Dream template

### ISSUE THREAD

**Issue by Ezyweb-uk** [microweber/microweber#721]
In the dev version with Dream template version 3.8 I'm seeing the following kind of messages in the content where I've added modules: `mw_replace_back_this_module_111-475632938-parser_modules96853306140 mw_replace_back_this_module_111-421760475-parser_modules96853306141` When I look in the html these messages are wrapped within tag tags.

**Comment by iceofice** [comment]
Hi there, I have faced a similar issue on admin, post content. The content text area is gone and it write something like this `mw_replace_back_this_textarea_0f27cc2f01c760ac1a8c14d3bc201afb` . Have you solved your issues? Please let me know, Thanks.
