### ISSUE TITLE
500 errors with no message

### ISSUE THREAD

**Issue by kennyparsons** [microweber/microweber#768]
When trying to do several operations on the server, I get 500 errors with no message in the body:
![example](https://user-images.githubusercontent.com/5930491/134943573-33f6ec8f-4fbe-45e3-849b-3ce05838caf4.png)

This is preventing me from doing most things on the server. I tried adding `APP_DEBUG=true` to my `.env` but the only log in the storage folder is the `laravel.log`. No error log gets reported. 

Edit: Just for kicks, I tried rebuilding with sqlite. No errors. Not sure if this helps figure out the issue. This does not mean it's fixed, as using a pg db is more reliable to me than sqlite.

**Comment by orbazan** [comment]
Same issue here. Try to also enable debug in config/app.php (second line, 'debug' => true,) see if it helps, it didn't change anything for me, still can't figure out these random Error 500's.

**Comment by batmine3** [comment]
Hello,

I've made severa search on this subject and I've possibly found the reason. If you look in the payload generated when you click on the "Add new offer" button, you can see the request is failing while parsing and creating the options for the select menu. 
![image](https://user-images.githubusercontent.com/43639258/145576254-14fe9fc2-2626-4ca2-a993-c1a6fe8bbee7.png)

I've decided to see in the php files where this menu is generated, it's in `microweber/userfiles/modules/shop/offers/edit_offer.php`. 

If you print out the values contained in the `$a_price` variable, you should noticed that the field `values_plain` don't exist but there is one with name as `value`.

By replacing this in the php file, you would be able to create offers.
![image](https://user-images.githubusercontent.com/43639258/145576961-88a772b5-078c-46ea-9e2c-7f8c4f07582c.png)
