### ISSUE TITLE
1.2.9 multilanguage issue

### ISSUE THREAD

**Issue by orbazan** [microweber/microweber#769]
Hello.
When using the latest 1.2.9 stable when changing anything on a page with live editor for another language the changes are not saved.
When using the latest 1.2.9-dev2 this is fixed, however if i have products in the shop in multiple languages then description in a language doesn't load. For instance, let's say i have product X in EN, FR and DE. There are descriptions for the product in all languages, however if i load the DE version of the product the description is in FR or EN. There really is no rule, descriptions are loaded not according to the language selected but apparently by chance. In 1.2.9 stable this works.

**Comment by peter-mw** [comment]
hi, this is fixed in version 1.2.10 , please update
