### ISSUE TITLE
Script timeout parsing live_edit.css with unclosed rule

### ISSUE THREAD

**Issue by hrvoje-grabusic** [microweber/microweber#780]
Hi,

If a css rule is not closed with } in live edit css the admin hangs and it is not possible to open the css editor to fix it.
The script times out trying to parse the css file.

The only way to fix it then is to open the live_edit.css file over ftp and fix it there.

**Comment by peter-mw** [comment]
Hi @hrvoje-grabusic   , can you post a screenshot or gif on how to reproduce this issue ?  

Do you edit the CSS from the CSS editor by typing code or in some other way  ?

**Comment by hrvoje-grabusic** [comment]
Hi,
In the CSS editor just save CSS rule without closing }
`.test {`

After that the admin will hang and in the JS console it will say script time out.

**Comment by peter-mw** [comment]
Hi @hrvoje-grabusic thanks for report, its fixed now in dev branch

Now it does not allow you to save if CSS is not valid

**Comment by hrvoje-grabusic** [comment]
Hi,
That's a good solution.
