### ISSUE TITLE
Docker build fails due to missing microweber-templates-new-world package

### ISSUE THREAD

**Issue by blues-man** [microweber/microweber#781]
Hello,

trying to build the container image, the build fails due to this error:

```
148/189 [=====================>------]  78%    Failed to download microweber-templates/new-world from dist: The "https://packages.microweberapi.com/domains/packages.microweberapi.com/dist/microweber-templates/new-world/microweber-templates-new-world-a9caf30ee5e27baa17755ce6998443fb7361a4ed-zip-2f70c1.zip" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Syncing microweber-templates/new-world (3.1) into cache
 ...

  [RuntimeException]
  Failed to execute git clone --mirror -- 'git@github.com:microweber-templates/new-world.git' '/root/.composer/cache/vcs/git-github.com-microweber-templates-new-world.git/'
```

The problem is that it is using SSH instead of HTTPS, and in this container SSH it's not installed. 
Easy fix it's to update the composer.lock to use HTTPS, and then the package URL could be also updated.

**Comment by Chen188** [comment]
This template is upgraded to 3.7, and it looks all other tags with prior version are deleted, which makes this issue happen.

**Comment by peter-mw** [comment]
Hello thanks for report, please use the `dev` branch for solution,  https://github.com/microweber/microweber/tree/dev

We are going to release new version this week which will fix the problem

**Comment by peter-mw** [comment]
tags are restored, seems @bobimicroweber have deleted them by mistake , now it should work 

thanks for report
