### ISSUE TITLE
Value of special price offer checkmark does not update when toggling it off.

### ISSUE THREAD

**Issue by RogerAntonio** [microweber/microweber#790]
**Issue:**
In the Admin UI, when editing a product, the "Make offer price for product" checkbox value remains 1, even when getting unchecked.
Because of this, the product will show the previously filled in special price instead of the original price.

**Expected result:**
The checkbox of the special offer should update its value correctly, allowing for templates to display the original price after disabling the special price offer.

**Issue in code:**
https://github.com/microweber/microweber/blob/2c8ba85984214ea033a3677d0169a15dd8498b47/userfiles/modules/shop/offers/special_price_field.php#L47

**Why is this an issue:**
My goal is to provide the visitor with both the original price and the offered price (if enabled) on the shop overview.
If both the original price and the special offers price are filled in, but the checkbox is unchecked (thus disabling the special price), the value of the checkbox still remains 1, and therefore the special price still gets shown even though we disabled the feature in the admin UI.

**Comment by bobimicroweber** [comment]
done!
