### ISSUE TITLE
The version of scssphp used is unmaintained

### ISSUE THREAD

**Issue by stof** [microweber/microweber#792]
Disclaimer: I'm not using microweber in any way. I'm one of the scssphp maintainer, and I was looking at packages using old versions of our library that still see usage in the install stats.

This package currently locks scssphp at version 1.4.1 while the latest version is 1.10.0. It would be great if the up-to-date version could be used.

Side note: versions of scssphp before 1.6.0 are failing to compile the latest versions of Bootstrap 4 and 5 properly.

**Comment by stof** [comment]
btw, I see that you also bundle the old `leafo/scssphp` package alongside `scssphp/scssphp`, without any usage of it. You might want to clean this.

**Comment by peter-mw** [comment]
hi @stof , thanks for noticing, we will clean up in next releases

**Comment by peter-mw** [comment]
We have updated the library now, thanks
