### ISSUE TITLE
The "View Order" option does not show the payment method name.

### ISSUE THREAD

**Issue by SAKIL2037** [microweber/microweber#795]
![image](https://user-images.githubusercontent.com/34392752/150556141-9beabd74-ca67-4668-aa51-1bf704fa36cd.png)

**Comment by peter-mw** [comment]
thanks for report, we will fix it

**Comment by SAKIL2037** [comment]
Thanks for your reply.
I fixed this and sent a pull request. If you like it, I will be happy if you merge it.
Pull Request Link: https://github.com/microweber/microweber/pull/796

**Comment by peter-mw** [comment]
fixed by @SAKIL2037
