### ISSUE TITLE
CALENDAR MODULE ISSUE

### ISSUE THREAD

**Issue by Artipug** [microweber/microweber#799]
Hello to you all, 
I'm so new with code and I have an issue about the calendar module that i've just download for Microweber. I passed the unzipped file to my server with winSCP (all the file as it was, to the Microweber file) and it didnt do much...
Can anyone help? What's the next step?

Thank you in advance!

**Comment by peter-mw** [comment]
Hello , you must unzip the files in the folder `userfiles/modules/calendar`

After that in the admin panel you must reload the modules

**Comment by Artipug** [comment]
Thank you so much!
