### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by talhak08** [microweber/microweber#804]
Please check out the report.
https://huntr.dev/bounties/09218d3f-1f6a-48ae-981c-85e86ad5ed8b/

**Comment by peter-mw** [comment]
hi, this issue is fixed, thanks for the report

**Comment by talhak08** [comment]
Hello Peter. The commit you sent me does not seem to be the solution.
https://www.github.com/microweber/microweber/commit/957d307178eb73e13fcfdffb364cee32bc6f9928
