### ISSUE TITLE
External Control of File Name or Path

### ISSUE THREAD

**Issue by talhak08** [microweber/microweber#808]
Hello there,

The vulnerability has been verified and fixed according to the maintainer but the provided commit is not the solution of the vulnerability. This misleads Microweber users. Please provide the accurate solution.

Report:
https://huntr.dev/bounties/09218d3f-1f6a-48ae-981c-85e86ad5ed8b/

Provided commit:
https://www.github.com/microweber/microweber/commit/957d307178eb73e13fcfdffb364cee32bc6f9928

**Comment by bobimicroweber** [comment]
https://github.com/microweber/microweber/commit/572bdc36b5b47923790016f6b961c8df53226855
https://github.com/microweber/microweber/commit/98d025467128ecc24195dcb56c533febc3c91af6

**Comment by talhak08** [comment]
Thanks for the fast response.

**Comment by peter-mw** [comment]
hi , the issue is fixed and new version is released
