### ISSUE TITLE
docker-compose file

### ISSUE THREAD

**Issue by Bassem-mistu-digital** [microweber/microweber#811]
Good morning, i have a problem with docker-compose.yml. When i running docker-compose build i receive "volumes must be a mapping" !!!!!

**Comment by peter-mw** [comment]
Hi, thanks for report. this issue it fixed now

**Comment by Bassem-mistu-digital** [comment]
@peter-mw thank you for your quick response.  Bro after running docker-compose up -d. what's the project url . Thanks
