### ISSUE TITLE
production.ERROR

### ISSUE THREAD

**Issue by gokkstudio** [microweber/microweber#825]
Can someone please decipher this log error for me?

[2022-03-10 11:21:26] production.ERROR: No parentNode, can't do after() {"exception":"[object] (Exception(code: 0): No parentNode, can't do after() at E:\\wamp64\\www\\microweber\\src\\MicroweberPackages\\App\\Utils\\lib\\phpQuery.php:3804)

[stacktrace]
#0 E:\\wamp64\\www\\microweber\\src\\MicroweberPackages\\App\\Utils\\lib\\phpQuery.php(3635): phpQueryObject->insert('<div class=\"edi...', 'after')
#1 E:\\wamp64\\www\\microweber\\src\\MicroweberPackages\\App\\Utils\\lib\\phpQuery.php(3275): phpQueryObject->after('<div class=\"edi...')
#2 E:\\wamp64\\www\\microweber\\src\\MicroweberPackages\\App\\Utils\\ParserEditFieldsTrait.php(479): phpQueryObject->replaceWith('<div class=\"edi...')
#3 E:\\wamp64\\www\\microweber\\src\\MicroweberPackages\\App\\Utils\\ParserProcessor.php(222): MicroweberPackages\\App\\Utils\\ParserProcessor->_replace_editable_fields('\
<!DOCTYPE html...', false, '\
<!DOCTYPE html...', false)
#4 E:\\wamp64\\www\\microweber\\src\\MicroweberPackages\\App\\Utils\\Parser.php(90): MicroweberPackages\\App\\Utils\\ParserProcessor->process('\
<!DOCTYPE html...', Array)
#5 E:\\wamp64\\www\\microweber\\src\\MicroweberPackages\\App\\Http\\Controllers\\FrontendController.php(1044): MicroweberPackages\\App\\Utils\\Parser->process('\
<!DOCTYPE html...')
#6 E:\\wamp64\\www\\microweber\\src\\MicroweberPackages\\App\\Http\\Controllers\\FrontendController.php(96): MicroweberPackages\\App\\Http\\Controllers\\FrontendController->frontend(Array)
#7 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): MicroweberPackages\\App\\Http\\Controllers\\FrontendController->index(Array)
#8 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('index', Array)
#9 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(MicroweberPackages\\App\\Http\\Controllers\\FrontendController), 'index')
#10 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(205): Illuminate\\Routing\\Route->runController()
#11 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(721): Illuminate\\Routing\\Route->run()
#12 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#13 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\AuthenticateSession.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 E:\\wamp64\\www\\microweber\\src\\MicroweberPackages\\App\\Http\\Middleware\\AuthenticateSessionForUser.php(23): Illuminate\\Session\\Middleware\\AuthenticateSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): MicroweberPackages\\App\\Http\\Middleware\\AuthenticateSessionForUser->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 E:\\wamp64\\www\\microweber\\src\\MicroweberPackages\\Multilanguage\\Http\\Middleware\\MultilanguageMiddleware.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): MicroweberPackages\\Multilanguage\\Http\\Middleware\\MultilanguageMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 E:\\wamp64\\www\\microweber\\src\\MicroweberPackages\\App\\Http\\Middleware\\XSS.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): MicroweberPackages\\App\\Http\\Middleware\\XSS->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(723): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#22 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#23 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(662): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#24 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#25 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(167): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#26 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#27 E:\\wamp64\\www\\microweber\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 E:\\wamp64\\www\\microweber\\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#40 E:\\wamp64\\www\\microweber\\src\\MicroweberPackages\\App\\Http\\Middleware\\StartSessionExtended.php(22): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): MicroweberPackages\\App\\Http\\Middleware\\StartSessionExtended->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#49 E:\\wamp64\\www\\microweber\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#50 E:\\wamp64\\www\\microweber\\index.php(90): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#51 {main}
"}

**Comment by gokkstudio** [comment]
Just checked on live domain. Same issue continues...

**Comment by RogerAntonio** [comment]
Since it's on both websites, could you describe what you did before this error?
Did you update/install/remove/edit anything?

**Comment by gokkstudio** [comment]
@RogerAntonio yeah, I guess I was changing logo in the navbar and slider images, that's the only thing I did... It's a fresh installation with default dummy content.

**Comment by peter-mw** [comment]
hi, checking this error, can you give more information how to reproduce ?

**Comment by gokkstudio** [comment]
It seems that I can't reproduce it again on the domain, but will keep monitoring if appears again. It might have been related exclusively to my localhost.
