### ISSUE TITLE
Instagram Feed

### ISSUE THREAD

**Issue by gokkstudio** [microweber/microweber#830]
Guys, I'm clueless how this module works, how do I configure it to show certain account feed?

![Screenshot-instagram-feed](https://user-images.githubusercontent.com/19394068/159001388-ce26a6af-96fa-4ac9-abdf-1893225cf32d.png)

**Comment by peter-mw** [comment]
Hi, the Instagram feed is not working at the moment as instagram api has been closed for external use. 
We need to find a way to use Instagram api and fix it
