### ISSUE TITLE
Moving to production

### ISSUE THREAD

**Issue by gokkstudio** [microweber/microweber#833]
Guys, when moving to production (from test domain to destination domain), are there any important things to do or not to do?, I was thinking something like:
- copy files to destination domain
- import database
- edit database.php file (only db info)
Anything else, delete cache manually?

Also, is it safe to use?:
1. Optimize assets loading
2. Enable full page cache
3. Run fullpage cache button thingy

**Comment by RogerAntonio** [comment]
Personally, I use Softaculous to automate the process. Some web hosts provide this feature.
I recommend using the optimizing assets feature and enabling full page caching yes.
