### ISSUE TITLE
Layout name does not show in layout live edit popup.

### ISSUE THREAD

**Issue by SAKIL2037** [microweber/microweber#834]
![image](https://user-images.githubusercontent.com/34392752/159658527-f95f33d9-a56a-47f9-869c-7850e6bc6f91.png)
if you show the layout name in this popup header.Then we will be the better understand for which popup is which layout.

**Comment by SAKIL2037** [comment]
Also this place.
![image](https://user-images.githubusercontent.com/34392752/159659482-ab0a2cb4-8a46-4341-bf00-d5fc65a57480.png)

**Comment by SAKIL2037** [comment]
Also this place.
![image](https://user-images.githubusercontent.com/34392752/159659670-c2c8eefa-cce4-48ef-bd5a-75f9a887fb58.png)

**Comment by peter-mw** [comment]
fixed , thanks for report
