### ISSUE TITLE
Gallery images in lighbox too small

### ISSUE THREAD

**Issue by gokkstudio** [microweber/microweber#840]
Guys, any reason for lightbox gallery images in "New World" theme to be so small on mobile, they are like tiny...
I've uploaded several images 1920x1080 and 1080x1350 which are normal on desktop resolutions but tiny on mobile.
How can I increase the size?

Automatic resizing is turned off.

**Comment by RogerAntonio** [comment]
You are talking about the MW.gallery right?
I have noticed the same using that.
I changed my template to use an alternative JQuery gallery where I could customize the size.

**Comment by gokkstudio** [comment]
Exactly! Could you share or tell me how to change to achieve that please?

**Comment by RogerAntonio** [comment]
I'm using [Magnific Popup](https://dimsemenov.com/plugins/magnific-popup/) as a plugin in my template.
Download it, put it in your template and add the following to the following files:

header.php
```
  <link rel="stylesheet" type="text/css" href="<?php print template_url(); ?>assets/plugins/magnific-popup/magnific-popup.css" />
```

footer.php
```
<script type="text/javascript" src="<?php print template_url(); ?>assets/plugins/magnific-popup/jquery.magnific-popup.min.js"></script>
<script>
// Better image pop-up gallery
$(document).ready(function () {
  $(".js-popup-gallery").magnificPopup({
    delegate: "a",
    type: "image",
    tLoading: "Loading image #%curr%...",
    mainClass: "mfp-img-mobile",
    gallery: {
      enabled: true,
      navigateByImgClick: true,
      preload: [0, 1], // Will preload 0 - before current, and 1 after the current image
    },
    image: {
      tError: '<a href="%url%">The image #%curr%</a> could not be loaded.',
      titleSrc: function (item) {
        return item.el.attr("title");
      },
    },
  });
});
</script>
```

Now you have to change the templates of your picture module to use this instead of the mw.gallery
```
# Some code precedes this
    <div class="gallery-container js-popup-gallery"> # Make sure to add the class js-popup-gallery on a container of the links to the images
      <?php $count = 0;
      foreach ($data as $item): ?> # this code will loop through your images and execute the following for each image:
          <a href="<?php print thumbnail($item['filename'], 1200); ?>" class="pictures picture-<?php print $item['id'];?>"> # Link to the large image
            <img src="<?php print thumbnail($item['filename'], 920); ?>" class="d-block" alt="<?php print $item['image_options']['title']; ?>"> # the smaller image that gets shown on the page (not the gallery)
          </a>
       <?php endif; ?>
    </div>
```

**Comment by gokkstudio** [comment]
Thanks @RogerAntonio, it's not working for me on "New World" theme which already has magnific popup files in theme assets and that got me confused.

I simply don't have time to pursue this, if you're interested in paid customization please send me a message..

**Comment by RogerAntonio** [comment]
> Thanks @RogerAntonio, it's not working for me on "New World" theme which already has magnific popup files in theme assets and that got me confused.
>
> I simply don't have time to pursue this, if you're interested in paid customization please send me a message..
Unfortunatly, I don't really mess with other themes. I have spent a lot of time on my own theme which I'm providing to my customers as a template option, it will keep updating with new layouts and options over time.
My [own website](http://weblama.be) was built with it. English translation is in progress so it's only in Dutch right now.
