### ISSUE TITLE
Translation not loading, normal behavior?

### ISSUE THREAD

**Issue by FractalMind** [microweber/microweber#841]
![2022-03-29_16-37](https://user-images.githubusercontent.com/5481933/160703022-cc58ba6b-158f-4629-ab05-7cedf9fd4909.png)
![2022-03-29_16-38](https://user-images.githubusercontent.com/5481933/160703032-3b73d112-0f7a-45c4-81ea-892c3448027a.png)
![2022-03-29_16-41](https://user-images.githubusercontent.com/5481933/160703380-a94f0f05-c7ff-4a6d-ba14-06bee5f4961c.png)

I can clearly see the translations in the resource folder but for some reason, they are not loaded when a language is added to the platform or used on the website. Is this normal or is something wrong on my end?

Thank you for your time

**Comment by peter-mw** [comment]
Fixed for 1.2.16, will release soon
