### ISSUE TITLE
Slider not working in production

### ISSUE THREAD

**Issue by FractalMind** [microweber/microweber#843]
Check out your own website the slider won't auto slide and have weird behavior like getting stuck between slides.

[https://templates.microweber.com/shopmag/](https://templates.microweber.com/shopmag/)

I have the same behavior at home with the warning:

![2022-04-01_19-46](https://user-images.githubusercontent.com/5481933/161355089-9aec02ba-9caa-4489-929a-5af37f44011c.png)

Is the fact that it can't find "bootstrap.bundle.min.js.map" related?

**Comment by RogerAntonio** [comment]
I don't know much about that template, but I can tell you that .map files probably have nothing to do with the issue.
Going from the link you provided it could be because there's only one slide.
This doesn't mean that this isn't an issue, it most definitely is. One slide should not be slide-able.

**Comment by FractalMind** [comment]
@RogerAntonio You are right... When the slider has pictures loaded it will auto-slide.

Thank you
