### ISSUE TITLE
Hi. May I ask why when I save the live edit and clear the cache, the page will be reloaded to the original interface, when f5 the page is normal again

### ISSUE THREAD

**Issue by tungpro97** [microweber/microweber#848]

**Comment by tungpro97** [comment]
tks, How to handle now?. Implemented the project

**Comment by trantuanngoctn97** [comment]
Hello. I got the same problem. I use live edit but sometimes, my website's appearance turn to original design. Please let me know when you release your update.
Thanks.

**Comment by trantuanngoctn97** [comment]
> Hi, this bug is fixed in the dev branch, we will release update soon

This bug also happends when i use clearcache() function but sometimes, i have to use clearcache(). How to use clearcache() appropriately? There is another function named cache_clear() with $cache_group, How to use it ? I can't find any instruction about using those functions. Please help me.

**Comment by SAKIL2037** [comment]
Hi @peter-mw can you please share me a commit link of this problem solution.

**Comment by peter-mw** [comment]
hi @SAKIL2037 , the fix is on this commit https://github.com/microweber/microweber/commit/c81835cc398381146f8d9099b0051dd81257a5c1

**Comment by SAKIL2037** [comment]
thanks @peter-mw

**Comment by trantuanngoctn97** [comment]
Hi @peter-mw can you help me how to delete cache in a specific folder (by domain) ?

**Comment by trantuanngoctn97** [comment]
Hi @peter-mw I want to set Default cache time longer for all data to reduce showing original template issue. How can i do that and do you think can it work ?
