### ISSUE TITLE
Changing section dummy text

### ISSUE THREAD

**Issue by gokkstudio** [microweber/microweber#852]
Guys, how to change the predifined "dummy" text of sections and keep the changes when updating MW?.

![mw-dummy-text](https://user-images.githubusercontent.com/19394068/163985093-649b4630-f578-401f-b768-f111e5bc952c.png)

**Comment by RogerAntonio** [comment]
I believe you can do this with translations.
Go in the translation settings, find the text and change it to what you want in the language you are using.
It's a bit scruffy to translate a text to something completely different, but besides this option, you can only change the text in the skin.php file which would overwrite when the template updates.

**Comment by peter-mw** [comment]
Hi, we have changed the text in the default template in this commit https://github.com/microweber-templates/new-world/commit/6ebeabb674223a7d9f27224c3fe8944229d9cd0a  and will release update soon

**Comment by gokkstudio** [comment]
Thanks guys, closing this one.
