### ISSUE TITLE
MaterialDesignIcons not found (error 404)

### ISSUE THREAD

**Issue by RogerAntonio** [microweber/microweber#853]
This icon font suddenly doesn't load in the icon picker anymore, I remember it working previously.
This is how it gets added to the page:
`mw.iconLoader().addIconSet('materialDesignIcons')`
Somehow the Path changed and it adds an extra `/css` in there (check image below)

This is the error it gives:
![image](https://user-images.githubusercontent.com/5510591/164507096-727c94ff-d18f-4921-8882-3f2323affd34.png)

MW Version: 1.2.13 (haven't checked in 1.2.14 yet)

**Comment by RogerAntonio** [comment]
It was and I just checked on last MW version, it's still there as well:
![image](https://user-images.githubusercontent.com/5510591/165350626-4942d921-f066-4d02-a3e0-b4e29663aaf8.png)

**Comment by peter-mw** [comment]
should be fixed now in 1.2.15
