### ISSUE TITLE
No module found fullpage_cache

### ISSUE THREAD

**Issue by gokkstudio** [microweber/microweber#854]
the little guy is gone somehow, how to get it back?

**Comment by peter-mw** [comment]
hi, can you post a screenshot ?

**Comment by gokkstudio** [comment]
There's only a blank page with the text on top: "No module found fullpage_cache" when I click on "run fullpage cache" button.. 

Nothing to see..

**Comment by peter-mw** [comment]
oh , someone disabled the module in the package manager, it should be back now

**Comment by gokkstudio** [comment]
Thanks, closing this one

**Comment by gokkstudio** [comment]
Guys, module won't appear by itself you know..

**Comment by gokkstudio** [comment]
Still gone, any help?
