### ISSUE TITLE
Updating through Softaculous removes whitelabel settings.

### ISSUE THREAD

**Issue by RogerAntonio** [microweber/microweber#857]
I understand that we now have a stand-alone-updater module which does what it should (whitelabel settings persist), but if you have to manage multiple websites, it's easier to bulk update all websites with automated backup through Softaculous.
But I have noticed with my last upgrade to 1.2.15 that all the settings of the whitelabel module were unset.
Which isn't the desired outcome when customers suddenly see another logo/companyname in their Admin UI.
As far as I could tell, no other settings or content was lost.

**Current result:**
Whitelabel settings get removed when upgrading to 1.2.15 (from 1.2.11).

**Expected result:**
Whitelabel settings get carried over from previous versions.

**Comment by peter-mw** [comment]
Strange. We will investigate

**Comment by RogerAntonio** [comment]
It did it again updating from 1.2.16 to 1.2.19, through Sofaculous.

**Comment by peter-mw** [comment]
oh sorry , need to check again

**Comment by peter-mw** [comment]
should be fixed now for the next versions

**Comment by nikitakothari06** [comment]
Hi @RogerAntonio 

I am from the Softaculous team. 

Apologies for the inconvenience caused to you. 

We have made the required changes and launched the same at Softaculous as well. Microweber team is soon to release the new version and this should resolve in new version.

**Just for the Information:** You can directly contact the Softaculous team if you face any issue in any of the scripts installed through Softaculous [here](https://softaculous.deskuss.com/). And we shall do our best to help you out.

**Comment by RogerAntonio** [comment]
Thank you so much, it's a great pleasure seeing issues getting resolved with seriousness and speed!

I will keep in mind to report Softaculous issues there as well @nikitakothari06 , thanks for the heads-up!
