### ISSUE TITLE
Translate "custom_fields"?

### ISSUE THREAD

**Issue by FractalMind** [microweber/microweber#859]
I try to translate the custom_fields to french

Material EN => Matériel FR
Steal EN => Aciel FR

### If not does it support the translation of tags?

![2022-05-06_18-26_1](https://user-images.githubusercontent.com/5481933/167223879-ddc92165-ee0f-4b8c-a231-198a11cefd02.png)
![2022-05-06_18-26](https://user-images.githubusercontent.com/5481933/167223882-1f4255b1-d8f4-4fa6-8834-7af0f7d1d427.png)
![2022-05-06_18-25](https://user-images.githubusercontent.com/5481933/167223883-166819c5-be93-446f-884e-6b7fbe83f74d.png)
![2022-05-06_18-24](https://user-images.githubusercontent.com/5481933/167223885-d43ce2ff-b203-4694-9dd0-433b0349d7fe.png)

**Comment by peter-mw** [comment]
Hi, for now translating values is not supported, but we will think how to add it in the future

**Comment by FractalMind** [comment]
> Hi, for now translating values is not supported, but we will think how to add it in the future

Thank you Peter. Would you know if tags are translated as of today?
