### ISSUE TITLE
Question about element class styling.

### ISSUE THREAD

**Issue by RogerAntonio** [microweber/microweber#873]
By default, ui.scss puts `transition: none !important;` on `.element` class.
Is there a reason for this?
Could it not be `transition: none;` without the important statement?
It's not a big issue, but I'm just wondering why this is the way it is.
If we transition on a tag that can be adjusted, our transitions get overwritten by the !important statement.
I know we can overwrite it by making our selector more specific and adding !important as well, but I'm not a fan of doing that.

![image](https://user-images.githubusercontent.com/5510591/170813388-b64ed2e7-d40f-4d81-a769-f72ab1fe17be.png)

**Comment by raikov** [comment]
The idea of this class is to be like a wrapper for content. 
The transition is set to none because when dragging, it may cause unpleasant experience for the user.
