### ISSUE TITLE
Full width gmaps

### ISSUE THREAD

**Issue by gokkstudio** [microweber/microweber#876]
yup, how to get the full width gmap module in New World?

**Comment by RogerAntonio** [comment]
Make sure the container around your google maps doesn't have the class ".container" or change it to ".container-fluid".
Here's how it's done in my template:
```
<section class="p-0 safe-mode nodrop" field="layout-skin-28-<?php print $params['id'] ?>" rel="module">
  <div class="container-fluid p-0">
    <module type="google_maps" class="p-0" />
  </div>
</section>
```

**Comment by gokkstudio** [comment]
Silly of me, forgot about the attributes field in editor. Thanks Roger! Closing this one.
