### ISSUE TITLE
How to setup SMTP for "PHP mail function"?

### ISSUE THREAD

**Issue by FractalMind** [microweber/microweber#878]
We are using the Multi-tenant feature therefore our goal is to setup `/config/mail.php`
So every tenant can send emails using the default `PHP mail function` where I guess it's configured in `/config/mail.php` 

Here what I get as error:

![2022-06-08_16-43](https://user-images.githubusercontent.com/5481933/172713551-87a4e2ff-3a5c-464b-b693-46fd81a599cf.png)

I tried to provoke an error with `smtpxxx` but it seems that `mail.php` is not even read by Microweber

![2022-06-08_16-47](https://user-images.githubusercontent.com/5481933/172714043-fb578210-f2c2-4749-9979-774db1b23c54.png)

Where should I configure the `PHP mail function`???

**Comment by FractalMind** [comment]
I understand but our goal is to have the email native with all tenants. 

Im not confortable sharing our AWS API keys to our tenants when infos are readable in the console when you load the form. 

Any experiance setting up email with Laravel? Any documentation for `PHP mail functions` ?

**Comment by peter-mw** [comment]
Hi,

We have added an option to use the system config 

![image](https://user-images.githubusercontent.com/5698247/173391426-93a4a0de-90b1-45b8-8e6d-6a4f1761d641.png)

**Comment by FractalMind** [comment]
Aight so a couple of things...

1. The wrong AWS credential I used
2. `PHP mail function` has a cache problem. The new  `Use system configuration` fixed the issue
3. "Forgot password" is not sending any email

First, **(The wrong AWS credential I used)**
 I ran into an AWS SES credential problem. When you create your SES account it can generate an SMTP user with credentials. For some retarded reason this user `access policy` is not compatible with the AWS_SDK_PHP

You need to create your own user with programmatical access and add `AmazonSESFullAccess`
![2022-06-13_19-55](https://user-images.githubusercontent.com/5481933/173466046-feb09fec-e140-4294-aa71-82f2dc4fb32f.png)

See this post [Amazon SES 403 Forbidden SignatureDoesNotMatch using Laravel 5.3](https://stackoverflow.com/questions/44197224/amazon-ses-403-forbidden-signaturedoesnotmatch-using-laravel-5-3)

/////////////////////////////////////////////////////////////

Second, **(`PHP mail function` has a cache problem. The new  `Use system configuration` fixed the issue)**

The `PHP mail function` seems to work with the new credentials but it looks like it has a cache problem

It works
![2022-06-13_18-35](https://user-images.githubusercontent.com/5481933/173466301-21af85ef-e239-429e-b529-e5e4bf8e8605.png)

But If I try again...
![2022-06-13_18-36](https://user-images.githubusercontent.com/5481933/173466308-7c6e86a5-ad0d-4220-a322-00e15fff8813.png)

If I delete the `email_transport` row, it works again
![2022-06-13_18-34](https://user-images.githubusercontent.com/5481933/173466476-1c1d3400-1791-4506-bed7-b0352f7147b1.png)

Thanks to @peter-mw  The new `Use system configuration` fixed the issue. I can now send test email
![Screenshot_20220613-200908_Gmail](https://user-images.githubusercontent.com/5481933/173469123-76c91f40-9821-48cb-95e8-4629ebc61858.jpg )

///////////////////////////////////////////////////////////////

Third, **( "Forgot password" is not sending any email )**

![2022-06-13_20-08](https://user-images.githubusercontent.com/5481933/173470244-c9b1f7ed-2dd0-496a-a9f6-59d6d0c3787e.png)


I try local + prod. It won't send an email.

I checked the logs. There's no error generated.

Thank you for your time

**Comment by FractalMind** [comment]
This issue was fixed in 1.2.18
