### ISSUE TITLE
Frontend Logout: 403 API UNAUTHORIZED

### ISSUE THREAD

**Issue by FractalMind** [microweber/microweber#881]
I can logout from the admin panel but if I create a front user and I try to logout

![Peek 2022-06-13 21-08](https://user-images.githubusercontent.com/5481933/173472324-6b819c76-7481-4ffb-ab44-1ee5497b946c.gif)

To log out I must clear the cookies or it will refuse to logout

**Comment by peter-mw** [comment]
hi, thanks for report fixed for version 1.2.17
