### ISSUE TITLE
Microweber not sending emails

### ISSUE THREAD

**Issue by FractalMind** [microweber/microweber#882]
**`Test emails` are working great on prod**
![Test_email](https://user-images.githubusercontent.com/5481933/173651104-c05b809b-fc66-4bca-960b-0003a91113ce.gif)

**Not working on `add user`**
![add_user](https://user-images.githubusercontent.com/5481933/173652782-d4953e84-57b7-49d6-9a97-3714cce04b7f.gif)

**Not working on `Forgot password Admin`**
![Forgot_password_admin](https://user-images.githubusercontent.com/5481933/173653168-4ad0d6f7-115c-43a3-8a5e-43516c8aedb2.gif)

**Not working on `Forgot password frontend user`**
![Forgot_password_user](https://user-images.githubusercontent.com/5481933/173653651-9e330554-a555-4971-a5a9-5a8d0e52a287.gif)

**Not working on `new orders`**
![Peek 2022-06-14 13-44](https://user-images.githubusercontent.com/5481933/173650861-fe9cfcc5-8ee2-4d9c-9220-83d58f81c3d6.gif)

**Comment by RogerAntonio** [comment]
I received my password reset mail for `forgot password admin` yesterday.
This was on a Fresh install `v1.2.16`
![image](https://user-images.githubusercontent.com/5510591/174073132-0708fc0b-3dd9-4b65-87ea-1bd8a4946223.png)

**Comment by FractalMind** [comment]
The unpublished product visibility issue was solved in the `dev branch`

But the mail issue still persist in a fresh installation of 1.2.17 `dev branch`

Please note: 

- The test email is working _(forgot password test, new order test)_
- But real life functional emails are not _(forgot password, new order)_
- The "From e-mail address" field seems to be ignored with `Read from Laravel - config/mail.php`. I MUST add  
`'from' => ['address' => 'example@example.com', 'name' => 'App Name'],` 
to `mail.php` to make it work

**Comment by samsong** [comment]
hi broken in 2.0.15. emails do not send. i have added a custom SMTP server. test email works. contact form email does not work. please help :( can't see any PHP errors. where are the microweber error logs? why is there no error showing at least!!!
