### ISSUE TITLE
Regular user still can't logout on 1.2.17 

### ISSUE THREAD

**Issue by FractalMind** [microweber/microweber#883]
- You can logout in the frontend if you are an admin **but not** a regular user
- You can logout **admin/regular user** in the backend with no issue

![Logout](https://user-images.githubusercontent.com/5481933/173673499-e4bf26d4-4bd2-43cb-9a2e-d40eefe83bd4.gif)

**Comment by peter-mw** [comment]
Hi, its working here. Please update the shopmag template to the last version
