### ISSUE TITLE
Mail issue with "Read from Laravel - config/mail.php"

### ISSUE THREAD

**Issue by FractalMind** [microweber/microweber#887]
On a fresh install of 1.2.18 the mail issue was solve for `SMTP mode` But not `Read from Laravel - config/mail.php`

- Mails are sent successfully with **test email** and **live email** with `SMTP mode`
- Mails are sent successfully with **test email**  with `Read from Laravel - config/mail.php`
- Mails are _failing_ **live email** with   with `Read from Laravel - config/mail.php`

I can see that 2 different functions are used to send emails:

(Test)_src/MicroweberPackages/Notification/Http/Controllers/Admin/NotificationController.php_
![2022-06-22_17-13_1](https://user-images.githubusercontent.com/5481933/175137354-e96dc492-c208-41c4-9a6c-7398738c6dd0.png)

(Live)_src/MicroweberPackages/User/Http/Controllers/UserForgotPasswordController.php_
![2022-06-22_17-13](https://user-images.githubusercontent.com/5481933/175137296-22c2c10b-b98a-435b-afd5-37374f0869ff.png)

Dump of **$request->only('email')** I get:
`{\"email\":\"myValidEmail@gmail.com\"}`

Dump of **$status = Password::sendResetLink(...)** I get:
`"passwords.sent"`

The issue seems to come from the configuration of 
`\Illuminate\Auth\Passwords\PasswordBroker`

**Comment by peter-mw** [comment]
hi, can you try again on the `dev` branch , we have made more fixes

**Comment by FractalMind** [comment]
Very close! It's almost all fixed

✅ On the `dev` branch emails are sending successfully for (**new orders + admin forgot password**) on `test mode` AND `live` 

☒ But **frontend forgot password** is not working
![Peek 2022-06-24 21-45](https://user-images.githubusercontent.com/5481933/175753796-3e13a267-b237-4155-8df0-4518b3dba777.gif)

**Comment by peter-mw** [comment]
hi, it should be fixed now in dev branch

**Comment by FractalMind** [comment]
I confirm everything is working now, good job!
