### ISSUE TITLE
Error 500 while importing translation .xlsx file

### ISSUE THREAD

**Issue by TheIceMagmaCube** [microweber/microweber#891]
Hi,
I downloaded a translation file from my microweber installation to make editing easier.

I tried to import it back, but I ran in a 500 error code "server error"
I run dev version.

Thanks for your help

**Comment by peter-mw** [comment]
Hi,

can you check what is the error on the file `storage/logs/laravel.log`   ?

**Comment by TheIceMagmaCube** [comment]
Thanks for your hard work!
