### ISSUE TITLE
Backend update of New World doesn't work

### ISSUE THREAD

**Issue by phausleitner** [microweber/microweber#894]
Hi, tried to update the New World template from version 5.2 to 5.4., MW 1.2.19.
The process seemed to be complete, after that packages reloaded, but still no change. Tried with two browsers, the same problem seems to be with the Bootsrap5 template.

**Comment by peter-mw** [comment]
Fixed, thanks, it was the wrong version number in config.php

**Comment by phausleitner** [comment]
Nice, thank you

**Comment by phausleitner** [comment]
Hi, it is fixed on Bootstrap5 template, but New World still seems to have that problem

**Comment by akies1** [comment]
still this bug is not fix
