### ISSUE TITLE
Updating the software (MW 1.3.0, PHP 8.1)

### ISSUE THREAD

**Issue by phausleitner** [microweber/microweber#911]
Hello, my hosting server was updated to PHP 8.1, so I went to update to the latest version of MW. But it keeps updating (15 minutes) and nothing happens (blank page on live page as well as in administration). Thanks for support
![obrázok](https://user-images.githubusercontent.com/108931257/182128639-ac2d4092-fc45-4b5b-b29d-a53535cc446f.png)

**Comment by phausleitner** [comment]
after 45 mins. still the same.. I think, I'll return to backup of previous MW version

**Comment by phausleitner** [comment]
After 1 hour, still the same, I think I'll get back to v1.2.21

**Comment by RogerAntonio** [comment]
I have the same issue using the stand-alone-updater on all previous versions.
It works, but I have to refresh/duplicate the tab in order for it to continue/try again.
But by doing so I also have to remove the downloaded and unpacked files manually otherwise my website doubles in size.

**Comment by RogerAntonio** [comment]
In my experience, Softaculous seems to be more reliable and offers to create a backup before you upgrade which you can rollback to if something goes wrong.
I keep testing out the SAU when it gets updated though to check out the improvements.

**Comment by peter-mw** [comment]
Hello, can you check if there is error in the file `storage/logs/laravel.log`

Also you can update manually by following this procedure https://github.com/microweber/microweber/blob/master/UPGRADING.md

**Comment by phausleitner** [comment]
Hi, thanks both for responses. Laravel.log was last modified almost a month ago. I refreshed and waited a bit more and update went done.
But 500 Server Error started to appear on admin sites. On laravel.log appeared this: "production.ERROR: file_exists(): File name is longer than the maximum allowed path length on this platform (4096): /home/html/XXXXX/mydomain.domainname/public_html/resources/views/&lt;!DOCTYPE html&gt; ... _followed by html source_.. "

**Comment by phausleitner** [comment]
returned from backup to MW 1.2.21

**Comment by phausleitner** [comment]
just to let you know.. Admin 500s fixed in 1.3.1, everything works fine, thanks for support
