### ISSUE TITLE
Issues when opening in docker

### ISSUE THREAD

**Issue by Crystal1462** [microweber/microweber#921]
I am not the greatest with docker but usually a project container works better then this experience for me.
(Windows 10 and docker works for other things so going with the setup is correct)

When I run the docker commands and try to start it I get this for the php-apache aspect of the container.  This is the error from inside docker when trying to run this.

Invalid extension name found in PHP_EXTENSIONS environment variable. Found: 'sodium'. Available extensions: amqp, apcu, ast, bcmath, bz2, calendar, ctype, curl, dba, dom, ds, enchant, exif, ffi, fileinfo, ftp, gd, gettext, gmp, grpc, iconv, igbinary, imagick, imap, intl, ldap, mailparse, mbstring, memcached, mongodb, msgpack, mysqli, mysqlnd, opcache, pcov, pdo, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, phar, posix, pspell, readline, redis, shmop, simplexml, snmp, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, uploadprogress, uuid, xdebug, xml, xmlreader, xmlrpc, xmlwriter, xsl, yaml, zip.
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - Root composer.json requires PHP extension ext-gd * but it is missing from your system. Install or enable PHP's gd extension.
  Problem 2
    - Root composer.json requires PHP extension ext-intl * but it is missing from your system. Install or enable PHP's intl extension.
  Problem 3
    - Root composer.json requires PHP extension ext-zip * but it is missing from your system. Install or enable PHP's zip extension.
  Problem 4
    - Root composer.json requires PHP extension ext-bcmath * but it is missing from your system. Install or enable PHP's bcmath extension.
  Problem 5
    - laravel/dusk is locked to version dev-master and an update of this package was not requested.
    - laravel/dusk dev-master requires ext-zip * -> it is missing from your system. Install or enable PHP's zip extension.
  Problem 6
    - moneyphp/money is locked to version v4.0.4 and an update of this package was not requested.
    - moneyphp/money v4.0.4 requires ext-bcmath * -> it is missing from your system. Install or enable PHP's bcmath extension.
  Problem 7
    - php-webdriver/webdriver is locked to version 1.12.1 and an update of this package was not requested.
    - php-webdriver/webdriver 1.12.1 requires ext-zip * -> it is missing from your system. Install or enable PHP's zip extension.
  Problem 8
    - phpoffice/phpspreadsheet is locked to version 1.16.0 and an update of this package was not requested.
    - phpoffice/phpspreadsheet 1.16.0 requires ext-gd * -> it is missing from your system. Install or enable PHP's gd extension.
  Problem 9
    - laravel/dusk dev-master requires ext-zip * -> it is missing from your system. Install or enable PHP's zip extension.
    - laravel/dusk 7.x-dev is an alias of laravel/dusk dev-master and thus requires it to be installed too.
    - laravel/dusk is locked to version 7.x-dev and an update of this package was not requested.

To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/8.1/cli/php.ini
    - /etc/php/8.1/cli/conf.d/10-opcache.ini
    - /etc/php/8.1/cli/conf.d/10-pdo.ini
    - /etc/php/8.1/cli/conf.d/15-xml.ini
    - /etc/php/8.1/cli/conf.d/20-calendar.ini
    - /etc/php/8.1/cli/conf.d/20-ctype.ini
    - /etc/php/8.1/cli/conf.d/20-curl.ini
    - /etc/php/8.1/cli/conf.d/20-dom.ini
    - /etc/php/8.1/cli/conf.d/20-exif.ini
    - /etc/php/8.1/cli/conf.d/20-fileinfo.ini
    - /etc/php/8.1/cli/conf.d/20-ftp.ini
    - /etc/php/8.1/cli/conf.d/20-gettext.ini
    - /etc/php/8.1/cli/conf.d/20-iconv.ini
    - /etc/php/8.1/cli/conf.d/20-mbstring.ini
    - /etc/php/8.1/cli/conf.d/20-phar.ini
    - /etc/php/8.1/cli/conf.d/20-posix.ini
    - /etc/php/8.1/cli/conf.d/20-readline.ini
    - /etc/php/8.1/cli/conf.d/20-shmop.ini
    - /etc/php/8.1/cli/conf.d/20-simplexml.ini
    - /etc/php/8.1/cli/conf.d/20-sockets.ini
    - /etc/php/8.1/cli/conf.d/20-sysvmsg.ini
    - /etc/php/8.1/cli/conf.d/20-sysvsem.ini
    - /etc/php/8.1/cli/conf.d/20-sysvshm.ini
    - /etc/php/8.1/cli/conf.d/20-tokenizer.ini
    - /etc/php/8.1/cli/conf.d/20-xmlreader.ini
    - /etc/php/8.1/cli/conf.d/20-xmlwriter.ini
    - /etc/php/8.1/cli/conf.d/20-xsl.ini
    - /etc/php/8.1/cli/conf.d/generated_conf.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-gd --ignore-platform-req=ext-intl --ignore-platform-req=ext-zip --ignore-platform-req=ext-bcmath --ignore-platform-req=ext-zip --ignore-platform-req=ext-bcmath --ignore-platform-req=ext-zip --ignore-platform-req=ext-gd --ignore-platform-req=ext-zip` to temporarily ignore these required extensions.

**Comment by peter-mw** [comment]
Hello,

Can you paste the command that you use to run the docker ?

**Comment by Crystal1462** [comment]
I think I ended up with something like docker-compose up 

Reasons:  No other install command provided between the github and docs seem to be consistent with commands nor requirements..  I have a shared host that has it offered for one click but as far as being able to install this on a local system to develop on it seems impossible.

**Comment by Crystal1462** [comment]
I still cannot get the docker container used with this to work but I was able to get other stacks to work correctly.  The issue that comes up from that is how slow docker can be when using a full stack on windows 10 it seems.  My end solution was to get it working with wamp which took just a few tweaks for the extensions.

If docker works for you I guess go ahead a close this.

**Comment by peter-mw** [comment]
Thanks for the report. There was indeed error.

It is fixed it now in the `dev` branch and you can run with `docker-compose up`

**Comment by Crystal1462** [comment]
Thanks, I will clear a little time today to test it and let you know :)

**Comment by Crystal1462** [comment]
It works great, only issue on my plate regarding it is it is still slow.  That isn't on you or the project, Seems to be windows 10 and WSL2 issue.  I need to do a little research on that to figure out a good solution.  Thank you for your time on this matter.
