### ISSUE TITLE
Error 500 afater install

### ISSUE THREAD

**Issue by cds-web-system** [microweber/microweber#927]
Hi,

When it finishes installing the web on my server(hestiacp) with php-fpm 8.1 and nginx, it shows the following error:

https://www.mydomain/admin?install_done=1
Page: 500 | Sever Error

Debug msg in browser:
file_exists(): File name is longer than the maximum allowed path length on this platform (4096): /home/cds/web/mydomain/public_html/resources/views/&lt;!DOCTYPE html&gt;
&lt;html lang=&quot;en-US&quot; dir=&quot;ltr&quot;&gt;
&lt;head&gt;
&lt;script src=&quot;https://www/mydomain/userfiles/cache/apijs_combined/api/combined/3896786236/admin_2282622326/1/3/0/js&quot;&gt;&lt;/script&gt;
&lt;link rel=&quot;stylesheet&quot; href=&quot;https://www/cds/tec/br/userfiles/modules/microweber/default/css&quot; type=&quot;text/css&quot; /&gt;&lt;link rel=&quot;stylesheet&quot; id=&quot;admin-main-css-style&quot; href=&quot;https://www/mydomain/userfiles/modules/microweber/api/libs/mw-ui/grunt/plugins/ui/css/main_with_mw/css&quot; type=&quot;text/css&quot; /&gt;
&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1/0&quot;&gt;
&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
&lt;meta name=&quot;robots&quot; content=&quot;noindex&quot;&gt;
&lt;script&gt;
mwAdmin = true;
admin_url = 'https://www/mydomain/admin/';
&lt;/script&gt;

Exception:
in[ /home/cds/web/mydomain/public_html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php ](https://www.mydomain.tec.br/admin/)(line 28)
in[ /home/cds/web/mydomain.tec.br/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php ](https://www.mydomain.tec.br/admin/)-> handleError (line 228)
HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
in[ /home/cds/web/mydomain.tec.br/public_html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php ](https://www.mydomain.tec.br/admin/)file_exists (line 28)

This error show when access mydomain.tec.br/admin, preventing access to the admin panel.

Any solution for this error?

Thanks!!

**Comment by peter-mw** [comment]
Fixed in version 1.3.1
