### ISSUE TITLE
TODO List?

### ISSUE THREAD

**Issue by hopeseekr** [microweber/microweber#94]
This isn't so much a bug as a request to help.

I believe in you guys. In fact, I think I must be one of your largest contributors (I donated +$1,000 about a year ago to you guys), because I'm also a PHP webdev and what you guys are making has blown my mind since the first Youtube demo.

AND! Because you aren't using a horrible license from the FSF (e.g., GPL, etc.), my corporation would like to help you guys out, too. 

Could you point me to a prioritized TODO list or merely list a feature or bug or two that you'd really like to get done? Otherwise, I'm just going to start tackling the buglist in a semi-random order.

What you guys are doing is important. It's literally reducing the entropy in the universe with each new client/user, and that's what we're all here to do, in the long-run.

Cheers!

**Comment by hopeseekr** [comment]
I just wanted to update. I've pushed about 2 dozen clients your way. 

I <3 what you guys have done and are doing! Let me know if there's any way I can help.

**Comment by peter-mw** [comment]
Hello @hopeseekr  we have todo list but its not public. I can add you on our Jira board so you can follow the road map there

**Comment by hopeseekr** [comment]
Man, I would absolutely love it! I'll sign a Contributor License Agreement and everything. I'd love to help this project more. I truly believe in it!

**Comment by peter-mw** [comment]
hi, i just added you on the board. pls check email for login link
