### ISSUE TITLE
New World template 5.5 - search icon

### ISSUE THREAD

**Issue by CabralFidalgo** [microweber/microweber#945]
MW 1.3.1
New World template 5.5

How to disable search icon since it does not work in a site without blog/shop?

**Comment by Radanovn** [comment]
Hello, there are Template settins from where you can stop the search or other settings if needed.
Please look at the screenshot below -

![image](https://user-images.githubusercontent.com/34285023/187391071-45daf9d2-e175-4540-a6c6-dc668bf0c3c6.png)

**Comment by RogerAntonio** [comment]
@Radanovn I think the screenshot you posted if from a previous issue you replied to.

**Comment by CabralFidalgo** [comment]
Yes, in Template Settings we have:
- Show search bar
- Show shopping cart
We can set to "no".
Thank you
