### ISSUE TITLE
Moving posts to categories don't add the parent category resulting in empty overviews.  

### ISSUE THREAD

**Issue by RogerAntonio** [microweber/microweber#964]
What currently happens when moving a post to a category:
![image](https://user-images.githubusercontent.com/5510591/200723590-efacc0dc-e2a8-4728-bdcf-afb509a09509.png)

Expected result:
![image](https://user-images.githubusercontent.com/5510591/200723653-08179d3d-7b06-45db-9dd2-a935d2353584.png)

Cause (I think) is the fact that the parent categories aren't automatically selected as they are when you create a post.
![image](https://user-images.githubusercontent.com/5510591/200724135-ef1f2091-3064-430d-b446-f9705e5866b3.png)

**Comment by peter-mw** [comment]
fixed
