### ISSUE TITLE
 Unable to prepare route [api_nosession/{all}] for serialization. Another route has already been assigned name [api].

### ISSUE THREAD

**Issue by Prathamesh-Patekar** [microweber/microweber#989]
giving error on running below command 
php artisan optimize 
Unable to prepare route [api_nosession/{all}] for serialization. Another route has already been assigned name [api].

  at vendor/laravel/framework/src/Illuminate/Routing/AbstractRouteCollection.php:219
    215▕             $route->name($name = $this->generateRouteName());
    216▕ 
    217▕             $this->add($route);
    218▕         } elseif (! is_null($symfonyRoutes->get($name))) {
  ➜ 219▕             throw new LogicException("Unable to prepare route [{$route->uri}] for serialization. Another route has already been assigned name [{$name}].");
    220▕         }
    221▕ 
    222▕         $symfonyRoutes->add($route->getName(), $route->toSymfonyRoute());
    223▕ 

      +30 vendor frames 
  31  artisan:33
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by peter-mw** [comment]
Hello, thanks for the report the issue has been fixed

**Comment by Prathamesh-Patekar** [comment]
> 

can your tell me with route name to change.

**Comment by peter-mw** [comment]
check this commit https://github.com/microweber/microweber/commit/9c4d9734880ca18ec42dc9821334a6b789d4eb21
