### ISSUE TITLE
xss vulnerability

### ISSUE THREAD

**Issue by Christynorl** [microweber/microweber#990]
hi,@peter-mw. I found an xss vulnerability, which may affect the security of users. I submitted the specific information in the huntr community, please click the link below to view
[link](https://huntr.dev/bounties/cf59deed-9d43-4552-acfd-43f38f3aabba/)
https://huntr.dev/bounties/cf59deed-9d43-4552-acfd-43f38f3aabba/

**Comment by peter-mw** [comment]
thanks for the report, i have added a fix
