### ISSUE TITLE
login and registration is not working in mobile view.

### ISSUE THREAD

**Issue by akies1** [microweber/microweber#995]
I am using new-world theme. but while using mobile view I am not able to log in or register in mobile

**Comment by peter-mw** [comment]
hi, thanks for report , we will check it

**Comment by akies1** [comment]
Hi, I have updated template from marketplace ,still it is not working.

**Comment by akies1** [comment]
Hi, I have updated the template from the marketplace, still it is not working in the new-world and shop mag template.

**Comment by akies1** [comment]
I have copied mobile_profile_link.php and pasted it into my template and that works for me. updating the template from the marketplace not working.
